#include "SkinConstants.hpp"


namespace Skins
{

	std::vector<std::string> WeaponNames = {
		"Glock-18",
		"P2000",
		"USP-S",
		"Dual Berettas",
		"P250",
		"Tec-9",
		"Five-Seven",
		"CZ-75",
		"Desert Eagle",
		"R8 Revolver",
		"Nova",
		"XM1014",
		"Sawed-Off",
		"MAG-7",
		"M249",
		"Negev",
		"MP9",
		"MAC-10",
		"MP7",
		"MP5",
		"UMP-45",
		"P90",
		"PP-Bizon",
		"FAMAS",
		"Galil",
		"M4A4",
		"AK-47",
		"M4A1-S",
		"SSG 08",
		"AUG",
		"SG 553",
		"AWP",
		"SCAR-20",
		"G3SG1",
		"Zeus x27",
		"C4",
		"Incendiary",
		"Molotov",
		"Decoy",
		"Flashbang",
		"HE Grenade",
		"Smoke"
	};

	std::vector<std::string> WeaponGroupNames = {
		"Pistol",
		"Heavy",
		"SMG",
		"Rifle",
		"Other",
	};

	std::vector<std::vector<Weapon>> WeaponGroupWeapons = {
		// Pistol
		{
			Weapon::Glock18,
			Weapon::P2000,
			Weapon::USPS,
			Weapon::DualBerettas,
			Weapon::P250,
			Weapon::Tec9,
			Weapon::FiveSeven,
			Weapon::CZ75,
			Weapon::DesertEagle,
			Weapon::R8Revolver,
		},
		// Heavy
		{
			Weapon::Nova,
			Weapon::XM1014,
			Weapon::SawedOff,
			Weapon::MAG7,
			Weapon::M249,
			Weapon::Negev,
		},
		// SMG
		{
			Weapon::MP9,
			Weapon::MAC10,
			Weapon::MP7,
			Weapon::MP5,
			Weapon::UMP45,
			Weapon::P90,
			Weapon::PPBizon,
		},
		// Rifle
		{
			Weapon::FAMAS,
			Weapon::Galil,
			Weapon::M4A4,
			Weapon::AK47,
			Weapon::M4A1S,
			Weapon::SSG08,
			Weapon::AUG,
			Weapon::SG553,
			Weapon::AWP,
			Weapon::SCAR20,
			Weapon::G3SG1,
		},
		// Other
		{
			Weapon::C4,
			Weapon::Incendiary,
			Weapon::Molotov,
			Weapon::Decoy,
			Weapon::Flashbang,
			Weapon::HE,
			Weapon::Smoke,
		},
	};

	std::vector<std::string> KnifeNames = {
		"Nomad",
		"Skeleton",
		"Survival",
		"Paracord",
		"Classic",
		"Bowie",
		"Butterfly",
		"Falchion",
		"Flip",
		"Gut",
		"Huntsman",
		"Karambit",
		"M9 Bayonet",
		"Navaja",
		"Shadow Daggers",
		"Stiletto",
		"Talon",
		"Ursus"
	};

	std::vector<std::string> GloveNames = {

	};

	std::vector<PaintKit> PaintKits
	{
		PaintKit(0, "None"),
        PaintKit(2, XOR("Groundwater"), (1ull << (uint64_t)Weapon::Glock18) | (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(3, XOR("Candy Apple"), (1ull << (uint64_t)Weapon::Glock18) | (1ull << (uint64_t)Weapon::FiveSeven) | (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::MAC10) | (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(5, XOR("Forest DDPAT"), (1ull << (uint64_t)Weapon::SawedOff) | (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(6, XOR("Arctic Camo"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(8, XOR("Desert Storm"), (1ull << (uint64_t)Weapon::M4A4) | (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(9, XOR("Bengal Tiger"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(10, XOR("Copperhead"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(11, XOR("Skulls"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(12, XOR("Crimson Web"), (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(13, XOR("Blue Streak"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(14, XOR("Red Laminate"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(15, XOR("Gunsmoke"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::MP7) | (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(16, XOR("Jungle Tiger"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(17, XOR("Urban DDPAT"), (1ull << (uint64_t)Weapon::Tec9) | (1ull << (uint64_t)Weapon::DesertEagle) | (1ull << (uint64_t)Weapon::MAC10) | (1ull << (uint64_t)Weapon::UMP45) | (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(20, XOR("Virus"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(21, XOR("Granite Marbleized"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(22, XOR("Contrast Spray"), (1ull << (uint64_t)Weapon::M249) | (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(25, XOR("Forest Leaves"), (1ull << (uint64_t)Weapon::USPS) | (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(26, XOR("Lichen Dashed"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(27, XOR("Bone Mask"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(28, XOR("Anodized Navy"), (1ull << (uint64_t)Weapon::DualBerettas) | (1ull << (uint64_t)Weapon::Negev) | (1ull << (uint64_t)Weapon::MP7) | (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(30, XOR("Snake Camo"), (1ull << (uint64_t)Weapon::SawedOff) | (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(32, XOR("Silver"), (1ull << (uint64_t)Weapon::P2000) | (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::MAG7) | (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(33, XOR("Hot Rod"), (1ull << (uint64_t)Weapon::MP9) | (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(34, XOR("Metallic DDPAT"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(36, XOR("Ossified"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(37, XOR("Blaze"), (1ull << (uint64_t)Weapon::DesertEagle) | (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(38, XOR("Fade"), (1ull << (uint64_t)Weapon::Glock18) | (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(39, XOR("Bulldozer"), (1ull << (uint64_t)Weapon::MAG7) | (1ull << (uint64_t)Weapon::MP9) | (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(40, XOR("Night"), (1ull << (uint64_t)Weapon::Glock18) | (1ull << (uint64_t)Weapon::DesertEagle) | (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(41, XOR("Copper"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(42, XOR("Blue Steel"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(43, XOR("Stained"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(44, XOR("Case Hardened"), (1ull << (uint64_t)Weapon::FiveSeven) | (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(46, XOR("Contractor"), (1ull << (uint64_t)Weapon::DualBerettas) | (1ull << (uint64_t)Weapon::FiveSeven) | (1ull << (uint64_t)Weapon::AUG) | (1ull << (uint64_t)Weapon::SCAR20) | (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(47, XOR("Colony"), (1ull << (uint64_t)Weapon::DualBerettas) | (1ull << (uint64_t)Weapon::FAMAS) | (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(48, XOR("Dragon Tattoo"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(51, XOR("Lightning Strike"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(60, XOR("Dark Water"), (1ull << (uint64_t)Weapon::USPS) | (1ull << (uint64_t)Weapon::FAMAS) | (1ull << (uint64_t)Weapon::M4A1S) | (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(61, XOR("Hypnotic"), (1ull << (uint64_t)Weapon::DesertEagle) | (1ull << (uint64_t)Weapon::MP9) | (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(62, XOR("Bloomstick"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(67, XOR("Cold Blooded"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(70, XOR("Carbon Fiber"), (1ull << (uint64_t)Weapon::MAG7) | (1ull << (uint64_t)Weapon::UMP45) | (1ull << (uint64_t)Weapon::PPBizon) | (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(71, XOR("Scorpion"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(72, XOR("Safari Mesh"), (1ull << (uint64_t)Weapon::AK47) | (1ull << (uint64_t)Weapon::AWP) | (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(73, XOR("Wings"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(74, XOR("Polar Camo"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(75, XOR("Blizzard Marbleized"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(76, XOR("Winter Forest"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(77, XOR("Boreal Forest"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(78, XOR("Forest Night"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(83, XOR("Orange DDPAT"), (1ull << (uint64_t)Weapon::SawedOff) | (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(84, XOR("Pink DDPAT"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(90, XOR("Mudder"), (1ull << (uint64_t)Weapon::DesertEagle) | (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(92, XOR("Cyanospatter"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(93, XOR("Caramel"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(95, XOR("Grassland"), (1ull << (uint64_t)Weapon::P2000) | (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(96, XOR("Blue Spruce"), (1ull << (uint64_t)Weapon::XM1014) | (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(98, XOR("Ultraviolet"), (1ull << (uint64_t)Weapon::MAC10) | (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(99, XOR("Sand Dune"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::MAG7) | (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(100, XOR("Storm"), (1ull << (uint64_t)Weapon::MAG7) | (1ull << (uint64_t)Weapon::MP9) | (1ull << (uint64_t)Weapon::P90) | (1ull << (uint64_t)Weapon::AUG) | (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(101, XOR("Tornado"), (1ull << (uint64_t)Weapon::MAC10) | (1ull << (uint64_t)Weapon::Galil) | (1ull << (uint64_t)Weapon::M4A4) | (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(102, XOR("Whiteout"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(104, XOR("Grassland Leaves"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(107, XOR("Polar Mesh"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(110, XOR("Condemned"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(111, XOR("Glacier Mesh"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(116, XOR("Sand Mesh"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(119, XOR("Sage Spray"), (1ull << (uint64_t)Weapon::SawedOff) | (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(122, XOR("Jungle Spray"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(124, XOR("Sand Spray"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(125, XOR("X-Ray"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(135, XOR("Urban Perforated"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(136, XOR("Waves Perforated"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(141, XOR("Orange Peel"), (1ull << (uint64_t)Weapon::FiveSeven) | (1ull << (uint64_t)Weapon::MP9) | (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(147, XOR("Jungle Dashed"), (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::SSG08) | (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(148, XOR("Sand Dashed"), (1ull << (uint64_t)Weapon::MP9) | (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(149, XOR("Urban Dashed"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(151, XOR("Jungle"), (1ull << (uint64_t)Weapon::FiveSeven) | (1ull << (uint64_t)Weapon::M249)),
        PaintKit(153, XOR("Demolition"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(154, XOR("Afterimage"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(155, XOR("Bullet Rain"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(156, XOR("Death by Kitty"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(157, XOR("Palm"), (1ull << (uint64_t)Weapon::MAC10) | (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(158, XOR("Walnut"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(159, XOR("Brass"), (1ull << (uint64_t)Weapon::Glock18) | (1ull << (uint64_t)Weapon::Tec9) | (1ull << (uint64_t)Weapon::PPBizon) | (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(162, XOR("Splash"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(164, XOR("Modern Hunter"), (1ull << (uint64_t)Weapon::P250) | (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::PPBizon) | (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(165, XOR("Splash Jam"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(166, XOR("Blaze Orange"), (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(167, XOR("Radiation Hazard"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(168, XOR("Nuclear Threat"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(169, XOR("Fallout Warning"), (1ull << (uint64_t)Weapon::XM1014) | (1ull << (uint64_t)Weapon::UMP45) | (1ull << (uint64_t)Weapon::P90)),
        PaintKit(170, XOR("Predator"), (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::M249) | (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(171, XOR("Irradiated Alert"), (1ull << (uint64_t)Weapon::SawedOff) | (1ull << (uint64_t)Weapon::MAG7) | (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(172, XOR("Black Laminate"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(174, XOR("BOOM"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(175, XOR("Scorched"), (1ull << (uint64_t)Weapon::MP7) | (1ull << (uint64_t)Weapon::UMP45) | (1ull << (uint64_t)Weapon::P90)),
        PaintKit(176, XOR("Faded Zebra"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(177, XOR("Memento"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(178, XOR("Doomkitty"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(179, XOR("Nuclear Threat"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(180, XOR("Fire Serpent"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(181, XOR("Corticera"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(182, XOR("Emerald Dragon"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(183, XOR("Overgrowth"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(184, XOR("Corticera"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(185, XOR("Golden Koi"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(186, XOR("Wave Spray"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(187, XOR("Zirka"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(188, XOR("Graven"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(189, XOR("Bright Water"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(190, XOR("Black Limba"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(191, XOR("Tempest"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(192, XOR("Shattered"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(193, XOR("Bone Pile"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(194, XOR("Spitfire"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(195, XOR("Demeter"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(196, XOR("Emerald"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(197, XOR("Anodized Navy"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(198, XOR("Hazard"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(199, XOR("Dry Season"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(200, XOR("Mayan Dreams"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(201, XOR("Palm"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(202, XOR("Jungle DDPAT"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(203, XOR("Rust Coat"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(204, XOR("Mosaico"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(205, XOR("Jungle"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(206, XOR("Tornado"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(207, XOR("Facets"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(208, XOR("Sand Dune"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(209, XOR("Groundwater"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(210, XOR("Anodized Gunmetal"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(211, XOR("Ocean Foam"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(212, XOR("Graphite"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(213, XOR("Ocean Foam"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(214, XOR("Graphite"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(215, XOR("X-Ray"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(216, XOR("Blue Titanium"), (1ull << (uint64_t)Weapon::Tec9) | (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(217, XOR("Blood Tiger"), (1ull << (uint64_t)Weapon::USPS) | (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(218, XOR("Hexane"), (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(219, XOR("Hive"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(220, XOR("Hemoglobin"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(221, XOR("Serum"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(222, XOR("Blood in the Water"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(223, XOR("Nightshade"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(224, XOR("Water Sigil"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(225, XOR("Ghost Camo"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(226, XOR("Blue Laminate"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(227, XOR("Electric Hive"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(228, XOR("Blind Spot"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(229, XOR("Azure Zebra"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(230, XOR("Steel Disruption"), (1ull << (uint64_t)Weapon::Glock18) | (1ull << (uint64_t)Weapon::P250)),
        PaintKit(231, XOR("Cobalt Disruption"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(232, XOR("Crimson Web"), (1ull << (uint64_t)Weapon::DesertEagle) | (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(233, XOR("Tropical Storm"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(234, XOR("Ash Wood"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(235, XOR("VariCamo"), (1ull << (uint64_t)Weapon::Tec9) | (1ull << (uint64_t)Weapon::Galil) | (1ull << (uint64_t)Weapon::M4A1S) | (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(236, XOR("Night Ops"), (1ull << (uint64_t)Weapon::USPS) | (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(237, XOR("Urban Rubble"), (1ull << (uint64_t)Weapon::DesertEagle) | (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(238, XOR("VariCamo Blue"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(240, XOR("CaliCamo"), (1ull << (uint64_t)Weapon::XM1014) | (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(241, XOR("Hunting Blind"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(242, XOR("Army Mesh"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(243, XOR("Gator Mesh"), (1ull << (uint64_t)Weapon::M249) | (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(244, XOR("Teardown"), (1ull << (uint64_t)Weapon::P90) | (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(245, XOR("Army Recon"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(246, XOR("Amber Fade"), (1ull << (uint64_t)Weapon::P2000) | (1ull << (uint64_t)Weapon::SawedOff) | (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(247, XOR("Damascus Steel"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(248, XOR("Red Quartz"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(249, XOR("Cobalt Quartz"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(250, XOR("Full Stop"), (1ull << (uint64_t)Weapon::SawedOff) | (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(251, XOR("Pit Viper"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(252, XOR("Silver Quartz"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(253, XOR("Acid Fade"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(254, XOR("Nitro"), (1ull << (uint64_t)Weapon::FiveSeven) | (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(255, XOR("Asiimov"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(256, XOR("The Kraken"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(257, XOR("Guardian"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(258, XOR("Mehndi"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(259, XOR("Redline"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(260, XOR("Pulse"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(261, XOR("Marina"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(262, XOR("Rose Iron"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(263, XOR("Rising Skull"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(264, XOR("Sandstorm"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(265, XOR("Kami"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(266, XOR("Magma"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(267, XOR("Cobalt Halftone"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(268, XOR("Tread Plate"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(269, XOR("The Fuschia Is Now"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(270, XOR("Victoria"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(271, XOR("Undertow"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(272, XOR("Titanium Bit"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(273, XOR("Heirloom"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(274, XOR("Copper Galaxy"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(275, XOR("Red FragCam"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(276, XOR("Panther"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(277, XOR("Stainless"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(278, XOR("Blue Fissure"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(279, XOR("Asiimov"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(280, XOR("Chameleon"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(281, XOR("Corporal"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(282, XOR("Redline"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(283, XOR("Trigon"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(284, XOR("Heat"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(285, XOR("Terrain"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(286, XOR("Antique"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(287, XOR("Pulse"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(288, XOR("Sergeant"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(289, XOR("Sandstorm"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(290, XOR("Guardian"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(291, XOR("Heaven Guard"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(293, XOR("Death Rattle"), (1ull << (uint64_t)Weapon::Glock18) | (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(294, XOR("Green Apple"), (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(295, XOR("Franklin"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(296, XOR("Meteorite"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(297, XOR("Tuxedo"), (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(298, XOR("Army Sheen"), (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::Negev) | (1ull << (uint64_t)Weapon::MP9) | (1ull << (uint64_t)Weapon::SG553) | (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(299, XOR("Caged Steel"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(300, XOR("Emerald Pinstripe"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(301, XOR("Atomic Alloy"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(302, XOR("Vulcan"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(303, XOR("Isaac"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(304, XOR("Slashed"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(305, XOR("Torque"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(306, XOR("Antique"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(307, XOR("Retribution"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(308, XOR("Kami"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(309, XOR("Howl"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(310, XOR("Curse"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(311, XOR("Desert Warfare"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(312, XOR("Cyrex"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(313, XOR("Orion"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(314, XOR("Heaven Guard"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(315, XOR("Poison Dart"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(316, XOR("Jaguar"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(317, XOR("Bratatat"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(318, XOR("Road Rash"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(319, XOR("Detour"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(320, XOR("Red Python"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(321, XOR("Master Piece"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(322, XOR("Nitro"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(323, XOR("Rust Coat"), (1ull << (uint64_t)Weapon::Nova) | (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(325, XOR("Chalice"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(326, XOR("Knight"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(327, XOR("Chainmail"), (1ull << (uint64_t)Weapon::P2000) | (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(328, XOR("Hand Cannon"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(329, XOR("Dark Age"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(330, XOR("Briar"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(332, XOR("Royal Blue"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(333, XOR("Indigo"), (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::MAC10) | (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(334, XOR("Twist"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(335, XOR("Module"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(336, XOR("Desert-Strike"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(337, XOR("Tatter"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(338, XOR("Pulse"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(339, XOR("Caiman"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(340, XOR("Jet Set"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(341, XOR("First Class"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(342, XOR("Leather"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(343, XOR("Commuter"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(344, XOR("Dragon Lore"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(345, XOR("First Class"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(346, XOR("Coach Class"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(347, XOR("Pilot"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(348, XOR("Red Leather"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(349, XOR("Osiris"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(350, XOR("Tigris"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(351, XOR("Conspiracy"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(352, XOR("Fowl Play"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(353, XOR("Water Elemental"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(354, XOR("Urban Hazard"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(355, XOR("Desert-Strike"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(356, XOR("Koi"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(357, XOR("Ivory"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(358, XOR("Supernova"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(359, XOR("Asiimov"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(360, XOR("Cyrex"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(361, XOR("Abyss"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(362, XOR("Labyrinth"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(363, XOR("Traveler"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(364, XOR("Business Class"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(365, XOR("Olive Plaid"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(366, XOR("Green Plaid"), (1ull << (uint64_t)Weapon::CZ75) | (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(367, XOR("Reactor"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(368, XOR("Setting Sun"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(369, XOR("Nuclear Waste"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(370, XOR("Bone Machine"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(371, XOR("Styx"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(372, XOR("Nuclear Garden"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(373, XOR("Contamination"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(374, XOR("Toxic"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(375, XOR("Radiation Hazard"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(376, XOR("Chemical Green"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(377, XOR("Hot Shot"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(378, XOR("Fallout Warning"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(379, XOR("Cerberus"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(380, XOR("Wasteland Rebel"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(381, XOR("Grinder"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(382, XOR("Murky"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(383, XOR("Basilisk"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(384, XOR("Griffin"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(385, XOR("Firestarter"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(386, XOR("Dart"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(387, XOR("Urban Hazard"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(388, XOR("Cartel"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(389, XOR("Fire Elemental"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(390, XOR("Highwayman"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(391, XOR("Cardiac"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(392, XOR("Delusion"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(393, XOR("Tranquility"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(394, XOR("Cartel"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(395, XOR("Man-o'-war"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(396, XOR("Urban Shock"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(397, XOR("Naga"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(398, XOR("Chatterbox"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(399, XOR("Catacombs"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(400, XOR("Dragon King"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(401, XOR("System Lock"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(402, XOR("Malachite"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(403, XOR("Deadly Poison"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(404, XOR("Muertos"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(405, XOR("Serenity"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(406, XOR("Grotto"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(407, XOR("Quicksilver"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(422, XOR("Elite Build"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(423, XOR("Armor Core"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(424, XOR("Worm God"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(425, XOR("Bronze Deco"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(426, XOR("Valence"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(427, XOR("Monkey Business"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(428, XOR("Eco"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(429, XOR("Djinn"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(430, XOR("Hyper Beast"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(431, XOR("Heat"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(432, XOR("Man-o'-war"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(433, XOR("Neon Rider"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(434, XOR("Origami"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(435, XOR("Pole Position"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(436, XOR("Grand Prix"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(437, XOR("Twilight Galaxy"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(438, XOR("Chronos"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(439, XOR("Hades"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(440, XOR("Icarus Fell"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(441, XOR("Minotaur's Labyrinth"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(442, XOR("Asterion"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(443, XOR("Pathfinder"), (1ull << (uint64_t)Weapon::P2000) | (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(444, XOR("Daedalus"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(445, XOR("Hot Rod"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(446, XOR("Medusa"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(447, XOR("Duelist"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(448, XOR("Pandora's Box"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(449, XOR("Poseidon"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(450, XOR("Moon in Libra"), (1ull << (uint64_t)Weapon::DualBerettas) | (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(451, XOR("Sun in Leo"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(452, XOR("Shipping Forecast"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(453, XOR("Emerald"), (1ull << (uint64_t)Weapon::DualBerettas) | (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(454, XOR("Para Green"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(455, XOR("Akihabara Accept"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(456, XOR("Hydroponic"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(457, XOR("Bamboo Print"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(458, XOR("Bamboo Shadow"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(459, XOR("Bamboo Forest"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(460, XOR("Aqua Terrace"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(462, XOR("Counter Terrace"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(463, XOR("Terrace"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(464, XOR("Neon Kimono"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(465, XOR("Orange Kimono"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(466, XOR("Crimson Kimono"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(467, XOR("Mint Kimono"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(468, XOR("Midnight Storm"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(469, XOR("Sunset Storm 1"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(470, XOR("Sunset Storm 2"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(471, XOR("Daybreak"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(472, XOR("Impact Drill"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(473, XOR("Seabird"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(474, XOR("Aquamarine Revenge"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(475, XOR("Hyper Beast"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(476, XOR("Yellow Jacket"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(477, XOR("Neural Net"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(478, XOR("Rocket Pop"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(479, XOR("Bunsen Burner"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(480, XOR("Evil Daimyo"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(481, XOR("Nemesis"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(482, XOR("Ruby Poison Dart"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(483, XOR("Loudmouth"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(484, XOR("Ranger"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(485, XOR("Handgun"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(486, XOR("Elite Build"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(487, XOR("Cyrex"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(488, XOR("Riot"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(489, XOR("Torque"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(490, XOR("Frontside Misty"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(491, XOR("Dualing Dragons"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(492, XOR("Survivor Z"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(493, XOR("Flux"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(494, XOR("Stone Cold"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(495, XOR("Wraiths"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(496, XOR("Nebula Crusader"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(497, XOR("Golden Coil"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(498, XOR("Rangeen"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(499, XOR("Cobalt Core"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(500, XOR("Special Delivery"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(501, XOR("Wingshot"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(502, XOR("Green Marine"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(503, XOR("Big Iron"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(504, XOR("Kill Confirmed"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(505, XOR("Scumbria"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(506, XOR("Point Disarray"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(507, XOR("Ricochet"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(508, XOR("Fuel Rod"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(509, XOR("Corinthian"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(510, XOR("Retrobution"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(511, XOR("The Executioner"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(512, XOR("Royal Paladin"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(514, XOR("Power Loader"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(515, XOR("Imperial"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(516, XOR("Shapewood"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(517, XOR("Yorick"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(518, XOR("Outbreak"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(519, XOR("Tiger Moth"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(520, XOR("Avalanche"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(521, XOR("Teclu Burner"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(522, XOR("Fade"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(523, XOR("Amber Fade"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(524, XOR("Fuel Injector"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(525, XOR("Elite Build"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(526, XOR("Photic Zone"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(527, XOR("Kumicho Dragon"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(528, XOR("Cartel"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(529, XOR("Valence"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(530, XOR("Triumvirate"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(532, XOR("Royal Legion"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(533, XOR("The Battlestar"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(534, XOR("Lapis Gator"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(535, XOR("Praetorian"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(536, XOR("Impire"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(537, XOR("Hyper Beast"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(538, XOR("Necropos"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(539, XOR("Jambiya"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(540, XOR("Lead Conduit"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(541, XOR("Fleet Flock"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(542, XOR("Judgement of Anubis"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(543, XOR("Red Astor"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(544, XOR("Ventilators"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(545, XOR("Orange Crash"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(546, XOR("Firefight"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(547, XOR("Spectre"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(548, XOR("Chantico's Fire"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(549, XOR("Bioleak"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(550, XOR("Oceanic"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(551, XOR("Asiimov"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(552, XOR("Fubar"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(553, XOR("Atlas"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(554, XOR("Ghost Crusader"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(555, XOR("Re-Entry"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(556, XOR("Primal Saber"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(557, XOR("Black Tie"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(583, XOR("Aristocrat"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(584, XOR("Phobos"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(585, XOR("Violent Daimyo"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(586, XOR("Wasteland Rebel"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(587, XOR("Mecha Industries"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(588, XOR("Desolate Space"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(589, XOR("Carnivore"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(590, XOR("Exo"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(591, XOR("Imperial Dragon"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(592, XOR("Iron Clad"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(593, XOR("Chopper"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(594, XOR("Harvester"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(595, XOR("Reboot"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(596, XOR("Limelight"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(597, XOR("Bloodsport"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(598, XOR("Aerial"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(599, XOR("Ice Cap"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(600, XOR("Neon Revolution"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(601, XOR("Syd Mead"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(602, XOR("Imprint"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(603, XOR("Directive"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(604, XOR("Roll Cage"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(605, XOR("Scumbria"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(606, XOR("Ventilator"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(607, XOR("Weasel"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(608, XOR("Petroglyph"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(609, XOR("Airlock"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(610, XOR("Dazzle"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(611, XOR("Grim"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(612, XOR("Powercore"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(613, XOR("Triarch"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(614, XOR("Fuel Injector"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(615, XOR("Briefing"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(616, XOR("Slipstream"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(622, XOR("Polymer"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(623, XOR("Ironwork"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(624, XOR("Dragonfire"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(625, XOR("Royal Consorts"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(626, XOR("Mecha Industries"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(627, XOR("Cirrus"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(628, XOR("Stinger"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(629, XOR("Black Sand"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(630, XOR("Sand Scale"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(631, XOR("Flashback"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(632, XOR("Buzz Kill"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(633, XOR("Sonar"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(634, XOR("Gila"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(635, XOR("Turf"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(636, XOR("Shallow Grave"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(637, XOR("Cyrex"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(638, XOR("Wasteland Princess"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(639, XOR("Bloodsport"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(640, XOR("Fever Dream"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(641, XOR("Jungle Slipstream"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(642, XOR("Blueprint"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(643, XOR("Xiangliu"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(644, XOR("Decimator"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(645, XOR("Oxide Blaze"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(646, XOR("Capillary"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(647, XOR("Crimson Tsunami"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(648, XOR("Emerald Poison Dart"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(649, XOR("Akoben"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(650, XOR("Ripple"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(651, XOR("Last Dive"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(652, XOR("Scaffold"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(653, XOR("Neo-Noir"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(654, XOR("Seasons"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(655, XOR("Zander"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(656, XOR("Orbit Mk01"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(657, XOR("Blueprint"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(658, XOR("Cobra Strike"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(659, XOR("Macabre"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(660, XOR("Hyper Beast"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(661, XOR("Sugar Rush"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(662, XOR("Oni Taiji"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(663, XOR("Briefing"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(664, XOR("Hellfire"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(665, XOR("Aloha"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(666, XOR("Hard Water"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(667, XOR("Woodsman"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(668, XOR("Red Rock"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(669, XOR("Death Grip"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(670, XOR("Death's Head"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(671, XOR("Cut Out"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(672, XOR("Metal Flowers"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(673, XOR("Morris"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(674, XOR("Triqua"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(675, XOR("The Empress"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(676, XOR("High Roller"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(677, XOR("Hunter"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(678, XOR("See Ya Later"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(679, XOR("Goo"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(680, XOR("Off World"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(681, XOR("Leaded Glass"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(682, XOR("Oceanic"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(683, XOR("Llama Cannon"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(684, XOR("Cracked Opal"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(685, XOR("Jungle Slipstream"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(686, XOR("Phantom"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(687, XOR("Tacticat"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(688, XOR("Exposure"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(689, XOR("Ziggy"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(690, XOR("Stymphalian"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(691, XOR("Mortis"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(692, XOR("Night Riot"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(693, XOR("Flame Test"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(694, XOR("Moonrise"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(695, XOR("Neo-Noir"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(696, XOR("Bloodsport"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(697, XOR("Black Sand"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(698, XOR("Lionfish"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(699, XOR("Wild Six"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(700, XOR("Urban Hazard"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(701, XOR("Grip"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(702, XOR("Aloha"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(703, XOR("SWAG-7"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(704, XOR("Arctic Wolf"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(705, XOR("Cortex"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(706, XOR("Oxide Blaze"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(707, XOR("Neon Rider"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(708, XOR("Amber Slipstream"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(709, XOR("Eco"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(710, XOR("Shred"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(711, XOR("Code Red"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(712, XOR("High Seas"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(713, XOR("Warhawk"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(714, XOR("Nightmare"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(715, XOR("Capillary"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(716, XOR("Toy Soldier"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(717, XOR("Traction"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(718, XOR("PAW"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(719, XOR("Powercore"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(720, XOR("Devourer"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(721, XOR("Survivalist"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(722, XOR("Snek-9"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(723, XOR("Eye of Athena"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(724, XOR("Wild Lotus"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(725, XOR("Day Lily"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(726, XOR("Sunset Lily"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(727, XOR("Midnight Lily"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(728, XOR("Teal Blossom"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(729, XOR("Crimson Blossom"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(730, XOR("Dark Blossom"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(731, XOR("Banana Leaf"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(732, XOR("Synth Leaf"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(733, XOR("Rust Leaf"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(734, XOR("Wild Lily"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(736, XOR("The Prince"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(737, XOR("Cinquedea"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(738, XOR("Orange Murano"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(739, XOR("Violet Murano"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(740, XOR("Navy Murano"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(741, XOR("Dark Filigree"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(742, XOR("Red Filigree"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(743, XOR("Orange Filigree"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(744, XOR("Baroque Red"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(745, XOR("Baroque Purple"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(746, XOR("Baroque Orange"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(747, XOR("Twin Turbo"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(748, XOR("Calf Skin"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(749, XOR("Vino Primo"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(750, XOR("Integrale"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(751, XOR("Hand Brake"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(752, XOR("Fade"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(753, XOR("Dirt Drop"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(754, XOR("Rust Coat"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(755, XOR("Slide"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(756, XOR("Gungnir"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(757, XOR("Emerald Jörmungandr"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(758, XOR("Flame Jörmungandr"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(759, XOR("Astral Jörmungandr"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(760, XOR("Frost Borre"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(761, XOR("Copper Borre"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(762, XOR("Red Stone"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(763, XOR("Mjölnir"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(775, XOR("Facility Sketch"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(776, XOR("Facility Negative"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(777, XOR("Facility Draft"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(778, XOR("Facility Dark"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(779, XOR("Random Access"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(780, XOR("Mainframe"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(781, XOR("Co-Processor"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(782, XOR("Motherboard"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(783, XOR("Bulkhead"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(784, XOR("Coolant"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(785, XOR("Mandrel"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(786, XOR("Exchanger"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(787, XOR("Core Breach"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(788, XOR("Acheron"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(789, XOR("Nuclear Garden"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(790, XOR("Cold Fusion"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(791, XOR("Remote Control"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(792, XOR("Control Panel"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(793, XOR("Converter"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(794, XOR("Sweeper"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(795, XOR("Safety Net"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(796, XOR("Check Engine"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(797, XOR("Brake Light"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(798, XOR("Nitro"), (1ull << (uint64_t)Weapon::R8Revolver) | (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(799, XOR("High Beam"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(800, XOR("Lab Rats"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(801, XOR("Asiimov"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(802, XOR("Momentum"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(803, XOR("Neo-Noir"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(804, XOR("Modest Threat"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(805, XOR("Mecha Industries"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(806, XOR("Scavenger"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(807, XOR("Signal"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(808, XOR("Oxide Blaze"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(809, XOR("Wood Fired"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(810, XOR("Phosphor"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(811, XOR("Magnesium"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(812, XOR("Pipe Down"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(813, XOR("Nevermore"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(814, XOR("Black Sand"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(815, XOR("Danger Close"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(816, XOR("Fubar"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(817, XOR("Flashback"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(835, XOR("Crypsis"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(836, XOR("Uncharted"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(837, XOR("Angry Mob"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(838, XOR("Atheris"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(839, XOR("Bamboozle"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(840, XOR("Whitefish"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(841, XOR("Light Rail"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(842, XOR("Akoben"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(843, XOR("Skull Crusher"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(844, XOR("The Emperor"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(845, XOR("Momentum"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(846, XOR("Gauss"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(847, XOR("Mischief"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(848, XOR("Verdigris"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(849, XOR("Off World"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(850, XOR("Incinegator"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(851, XOR("Moonrise"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(859, XOR("Emerald Quartz"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(860, XOR("Pyre"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(861, XOR("Barricade"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(862, XOR("Moss Quartz"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(863, XOR("Night Borre"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(864, XOR("Candy Apple"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(865, XOR("Stone Mosaico"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(866, XOR("Canal Spray"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(867, XOR("Stained Glass"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(868, XOR("Sea Calico"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(869, XOR("Sundown"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(870, XOR("Jungle Thicket"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(871, XOR("Surfwood"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(872, XOR("Bamboo Garden"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(873, XOR("Seabird"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(884, XOR("Embargo"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(885, XOR("Rat Rod"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(886, XOR("Arctic Wolf"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(887, XOR("Containment Breach"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(888, XOR("Acid Wash"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(889, XOR("Decimator"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(890, XOR("Plume"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(891, XOR("Black Sand"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(892, XOR("Memento"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(893, XOR("Neon Ply"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(894, XOR("Obsidian"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(895, XOR("Balance"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(896, XOR("Torn"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(897, XOR("Colony IV"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(898, XOR("Stalker"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(899, XOR("Bloodshot"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(900, XOR("Warbird"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(902, XOR("Aztec"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(903, XOR("Elite 1.6"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(904, XOR("Decommissioned"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(905, XOR("Flash Out"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(906, XOR("Buddy"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(907, XOR("Inferno"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(908, XOR("Classic Crate"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(909, XOR("Popdog"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(910, XOR("Hydra"), (1ull << (uint64_t)Weapon::MP9)),
        PaintKit(911, XOR("Nostalgia"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(913, XOR("Death by Puppy"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(914, XOR("Assault"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(915, XOR("Agent"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(916, XOR("Plastique"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(917, XOR("Wildfire"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(918, XOR("Sacrifice"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(919, XOR("Commemoration"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(920, XOR("Boroque Sand"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(941, XOR("Phantom Disruptor"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(942, XOR("Tom Cat"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(943, XOR("Capillary"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(944, XOR("Distressed"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(945, XOR("Blue Ply"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(946, XOR("Player Two"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(947, XOR("Disco Tech"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(948, XOR("Justice"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(949, XOR("Desert Strike"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(950, XOR("Prototype"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(951, XOR("Acid Etched"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(952, XOR("Bone Forged"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(953, XOR("Apocalypto"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(954, XOR("Enforcer"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(955, XOR("Darkwing"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(956, XOR("Fever Dream"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(957, XOR("Bullet Queen"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(958, XOR("Ultralight"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(959, XOR("Legion of Anubis"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(960, XOR("Gnarled"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(961, XOR("Monster Call"), (1ull << (uint64_t)Weapon::MAG7)),
        PaintKit(962, XOR("Printstream"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(963, XOR("Vogue"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(964, XOR("Brother"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(965, XOR("Allure"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(966, XOR("Ol' Rusty"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(967, XOR("Mainframe 001"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(968, XOR("Cassette"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(969, XOR("Freight"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(970, XOR("Entombed"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(971, XOR("Tooth Fairy"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(972, XOR("Connexion"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(973, XOR("Runic"), (1ull << (uint64_t)Weapon::PPBizon)),
        PaintKit(974, XOR("Kitbash"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(975, XOR("Exoskeleton"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(976, XOR("Vendetta"), (1ull << (uint64_t)Weapon::CZ75)),
        PaintKit(977, XOR("Cocoa Rampage"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(978, XOR("Dezastre"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(979, XOR("Fairy Tale"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(980, XOR("Digital Mesh"), (1ull << (uint64_t)Weapon::G3SG1)),
        PaintKit(981, XOR("Vandal"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(982, XOR("Contaminant"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(983, XOR("Deep Relief"), (1ull << (uint64_t)Weapon::M249)),
        PaintKit(984, XOR("Printstream"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(985, XOR("Cyber Security"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(986, XOR("Condition Zero"), (1ull << (uint64_t)Weapon::MP5)),
        PaintKit(987, XOR("Clear Polymer"), (1ull << (uint64_t)Weapon::Nova)),
        PaintKit(988, XOR("Neo-Noir"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(989, XOR("Parallax"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(990, XOR("Gold Bismuth"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(991, XOR("Monster Mashup"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(992, XOR("The Bronze"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(993, XOR("Global Offensive"), (1ull << (uint64_t)Weapon::M4A4)),
        PaintKit(994, XOR("Charter"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(995, XOR("Surveillance"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(996, XOR("Threat Detected"), (1ull << (uint64_t)Weapon::SSG08)),
        PaintKit(997, XOR("Dispatch"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(998, XOR("Switch Board"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(999, XOR("Prime Conspiracy"), (1ull << (uint64_t)Weapon::FAMAS)),
        PaintKit(1000, XOR("Run and Hide"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(1001, XOR("Welcome to the Jungle"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(1002, XOR("Berries And Cherries"), (1ull << (uint64_t)Weapon::FiveSeven)),
        PaintKit(1003, XOR("Crime Scene"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(1004, XOR("X-Ray"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(1005, XOR("Heist"), (1ull << (uint64_t)Weapon::DualBerettas)),
        PaintKit(1006, XOR("Night Heist"), (1ull << (uint64_t)Weapon::DesertEagle)),
        PaintKit(1007, XOR("Vault Heist"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(1008, XOR("Houndstooth"), (1ull << (uint64_t)Weapon::UMP45)),
        PaintKit(1009, XOR("Hot Snakes"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(1010, XOR("Phoenix Chalk"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(1011, XOR("Phoenix Marker"), (1ull << (uint64_t)Weapon::R8Revolver)),
        PaintKit(1012, XOR("Phoenix Stencil"), (1ull << (uint64_t)Weapon::Negev)),
        PaintKit(1013, XOR("Phoenix Blacklight"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(1014, XOR("Clay Ambush"), (1ull << (uint64_t)Weapon::SawedOff)),
        PaintKit(1015, XOR("Tiger Pit"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(1016, XOR("Franklin"), (1ull << (uint64_t)Weapon::Glock18)),
        PaintKit(1017, XOR("Blue Phosphor"), (1ull << (uint64_t)Weapon::M4A1S)),
        PaintKit(1018, XOR("Panthera onca"), (1ull << (uint64_t)Weapon::AK47)),
        PaintKit(1019, XOR("Panther Camo"), (1ull << (uint64_t)Weapon::P2000)),
        PaintKit(1020, XOR("Ancient Earth"), (1ull << (uint64_t)Weapon::P90)),
        PaintKit(1021, XOR("Ancient Lore"), (1ull << (uint64_t)Weapon::XM1014)),
        PaintKit(1022, XOR("Lush Ruins"), (1ull << (uint64_t)Weapon::SG553)),
        PaintKit(1023, XOR("Tall Grass"), (1ull << (uint64_t)Weapon::MP7)),
        PaintKit(1024, XOR("Blast From the Past"), (1ull << (uint64_t)Weapon::Tec9)),
        PaintKit(1025, XOR("Gold Brick"), (1ull << (uint64_t)Weapon::MAC10)),
        PaintKit(1026, XOR("Fade"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(1027, XOR("Target Acquired"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(1028, XOR("Magna Carta"), (1ull << (uint64_t)Weapon::SCAR20)),
        PaintKit(1029, XOR("Silk Tiger"), (1ull << (uint64_t)Weapon::AWP)),
        PaintKit(1030, XOR("Bengal Tiger"), (1ull << (uint64_t)Weapon::P250)),
        PaintKit(1031, XOR("Ancient Visions"), (1ull << (uint64_t)Weapon::USPS)),
        PaintKit(1032, XOR("Dusk Ruins"), (1ull << (uint64_t)Weapon::Galil)),
        PaintKit(1033, XOR("Carved Jade"), (1ull << (uint64_t)Weapon::AUG)),
        PaintKit(1034, XOR("Ancient Ritual"), (1ull << (uint64_t)Weapon::G3SG1)),
	};
};

/*
std::vector<std::vector<std::string>> Skins::WeaponGroups = {
	{"Pistol", "pistol",
		"Glock-18", "glock",
		"P2000", "hkp2000",
		"USP-S", "usp_silencer",
		"Dual Berettas", "elite", // lol wtf valve
		"P250", "p250",
		"Tec-9", "tec9",
		"Five-Seven", "fn57",
		"CZ-75", "cz75a",
		"Desert Eagle",	"deagle",
		"R8 Revolver", "revolver"
	},
	{"Heavy", "heavy",
		"Nova", "nove",
		"XM1014", "xm1014",
		"Sawed-Off", "sawedoff", // TODO check if this is right
		"MAG-7", "mag7",
		"M249", "m249",
		"Negev", "negev",
	},
	{"SMG", "smg",
		"MP9", "mp9", 
		"MAC-10", "mac10", 
		"MP7", "mp7", 
		"MP5", "mp5sd", 
		"UMP-45", "ump45", 
		"P90", "p90", 
		"PP-Bizon", "bizon"
	},
	{"Rifle", "rifle",
		"FAMAS", "famas",
		"Galil", "galilar",
		"M4A4", "m4a4",
		"AK-47", "ak47",
		"M4A1-S", "m4a1_silencer",
		"SSG 08", "ssg08",
		"AUG", "aug",
		"SG 553", "sg556", // valve why, wtf?
		"AWP", "awp",
		"SCAR-20", "scar20",
		"G3SG1", "g3sg1"
	},
	{"Other", "other",
		"Zeus x27", "taser",
		"C4", "c4",
		"Incendiary", "incgrenade",
		"Molotov", "molotov", 
		"Decoy", "decoy",
		"Flashbang", "flashbang",
		"HE Grenade", "hegrenade", 
		"Smoke", "smokegrenade"
	},
};
*/