#include "SkinConstants.hpp"


namespace Skins
{

	std::vector<std::string> WeaponNames = {
		"Glock-18",
		"P2000",
		"USP-S",
		"Dual Berettas",
		"P250",
		"Tec-9",
		"Five-Seven",
		"CZ-75",
		"Desert Eagle",
		"R8 Revolver",
		"Nova",
		"XM1014",
		"Sawed-Off",
		"MAG-7",
		"M249",
		"Negev",
		"MP9",
		"MAC-10",
		"MP7",
		"MP5",
		"UMP-45",
		"P90",
		"PP-Bizon",
		"FAMAS",
		"Galil",
		"M4A4",
		"AK-47",
		"M4A1-S",
		"SSG 08",
		"AUG",
		"SG 553",
		"AWP",
		"SCAR-20",
		"G3SG1",
		"Zeus x27",
		"C4",
		"Incendiary",
		"Molotov",
		"Decoy",
		"Flashbang",
		"HE Grenade",
		"Smoke"
	};

	std::vector<std::string> WeaponGroupNames = {
		"Pistol",
		"Heavy",
		"SMG",
		"Rifle",
		"Other",
	};

	std::vector<std::vector<Weapon>> WeaponGroupWeapons = {
		// Pistol
		{
			Weapon::Glock18,
			Weapon::P2000,
			Weapon::USPS,
			Weapon::DualBerettas,
			Weapon::P250,
			Weapon::Tec9,
			Weapon::FiveSeven,
			Weapon::CZ75,
			Weapon::DesertEagle,
			Weapon::R8Revolver,
		},
		// Heavy
		{
			Weapon::Nova,
			Weapon::XM1014,
			Weapon::SawedOff,
			Weapon::MAG7,
			Weapon::M249,
			Weapon::Negev,
		},
		// SMG
		{
			Weapon::MP9,
			Weapon::MAC10,
			Weapon::MP7,
			Weapon::MP5,
			Weapon::UMP45,
			Weapon::P90,
			Weapon::PPBizon,
		},
		// Rifle
		{
			Weapon::FAMAS,
			Weapon::Galil,
			Weapon::M4A4,
			Weapon::AK47,
			Weapon::M4A1S,
			Weapon::SSG08,
			Weapon::AUG,
			Weapon::SG553,
			Weapon::AWP,
			Weapon::SCAR20,
			Weapon::G3SG1,
		},
		// Other
		{
			Weapon::C4,
			Weapon::Incendiary,
			Weapon::Molotov,
			Weapon::Decoy,
			Weapon::Flashbang,
			Weapon::HE,
			Weapon::Smoke,
		},
	};

	std::vector<std::string> KnifeNames = {
		"Nomad",
		"Skeleton",
		"Survival",
		"Paracord",
		"Classic",
		"Bowie",
		"Butterfly",
		"Falchion",
		"Flip",
		"Gut",
		"Huntsman",
		"Karambit",
		"M9 Bayonet",
		"Navaja",
		"Shadow Daggers",
		"Stiletto",
		"Talon",
		"Ursus"
	};

	std::vector<std::string> GloveNames = {

	};

	std::vector<PaintKit> PaintKits
	{
		PaintKit(0, "default", "None"),
		PaintKit(2, "-", "Groundwater", {Weapon::Glock18, Weapon::Tec9}),
		PaintKit(3, "-", "Candy Apple", {Weapon::Glock18, Weapon::FiveSeven, Weapon::Nova, Weapon::MAC10, Weapon::PPBizon}),
		PaintKit(5, "-", "Forest DDPAT", {Weapon::SawedOff, Weapon::MP7}),
		PaintKit(6, "-", "Arctic Camo", {Weapon::G3SG1}),
		PaintKit(8, "-", "Desert Storm", {Weapon::M4A4, Weapon::G3SG1}),
		PaintKit(9, "-", "Bengal Tiger", {Weapon::AUG}),
		PaintKit(10, "-", "Copperhead", {Weapon::AUG}),
		PaintKit(11, "-", "Skulls", {Weapon::MP7}),
		PaintKit(12, "-", "Crimson Web", {Weapon::CZ75, Weapon::R8Revolver}),
		PaintKit(13, "-", "Blue Streak", {Weapon::PPBizon}),
		PaintKit(14, "-", "Red Laminate", {Weapon::AK47}),
		PaintKit(15, "-", "Gunsmoke", {Weapon::P250, Weapon::MP7, Weapon::UMP45}),
		PaintKit(16, "-", "Jungle Tiger", {Weapon::M4A4}),
		PaintKit(17, "-", "Urban DDPAT", {Weapon::Tec9, Weapon::DesertEagle, Weapon::MAC10, Weapon::UMP45, Weapon::M4A4}),
		PaintKit(20, "-", "Virus", {Weapon::P90}),
		PaintKit(21, "-", "Granite Marbleized", {Weapon::P2000}),
		PaintKit(22, "-", "Contrast Spray", {Weapon::M249, Weapon::FAMAS}),
		PaintKit(25, "-", "Forest Leaves", {Weapon::USPS, Weapon::Nova, Weapon::PPBizon}),
		PaintKit(26, "-", "Lichen Dashed", {Weapon::SSG08}),
		PaintKit(27, "-", "Bone Mask", {Weapon::P250, Weapon::R8Revolver}),
		PaintKit(28, "-", "Anodized Navy", {Weapon::DualBerettas, Weapon::Negev, Weapon::MP7, Weapon::SG553}),
		PaintKit(30, "-", "Snake Camo", {Weapon::SawedOff, Weapon::AWP}),
		PaintKit(32, "-", "Silver", {Weapon::P2000, Weapon::CZ75, Weapon::MAG7, Weapon::MAC10}),
		PaintKit(33, "-", "Hot Rod", {Weapon::MP9, Weapon::AUG}),
		PaintKit(34, "-", "Metallic DDPAT", {Weapon::P250, Weapon::MAG7}),
		PaintKit(36, "-", "Ossified", {Weapon::Tec9}),
		PaintKit(37, "-", "Blaze", {Weapon::DesertEagle, Weapon::UMP45}),
		PaintKit(38, "-", "Fade", {Weapon::Glock18, Weapon::MAC10}),
		PaintKit(39, "-", "Bulldozer", {Weapon::MAG7, Weapon::MP9, Weapon::SG553}),
		PaintKit(40, "-", "Night", {Weapon::Glock18, Weapon::DesertEagle, Weapon::R8Revolver}),
		PaintKit(41, "-", "Copper", {Weapon::SawedOff}),
		PaintKit(42, "-", "Blue Steel", {Weapon::XM1014}),
		PaintKit(43, "-", "Stained", {Weapon::DualBerettas}),
		PaintKit(44, "-", "Case Hardened", {Weapon::FiveSeven, Weapon::AK47}),
		PaintKit(46, "-", "Contractor", {Weapon::DualBerettas, Weapon::FiveSeven, Weapon::AUG, Weapon::SCAR20, Weapon::G3SG1}),
		PaintKit(47, "-", "Colony", {Weapon::DualBerettas, Weapon::FAMAS, Weapon::AUG}),
		PaintKit(48, "-", "Dragon Tattoo", {Weapon::Glock18}),
		PaintKit(51, "-", "Lightning Strike", {Weapon::AWP}),
		PaintKit(60, "-", "Dark Water", {Weapon::USPS, Weapon::FAMAS, Weapon::M4A1S, Weapon::SSG08}),
		PaintKit(61, "-", "Hypnotic", {Weapon::DesertEagle, Weapon::MP9, Weapon::SG553}),
		PaintKit(62, "-", "Bloomstick", {Weapon::Nova}),
		PaintKit(67, "-", "Cold Blooded", {Weapon::P90}),
		PaintKit(70, "-", "Carbon Fiber", {Weapon::MAG7, Weapon::UMP45, Weapon::PPBizon, Weapon::SCAR20}),
		PaintKit(71, "-", "Scorpion", {Weapon::P2000}),
		PaintKit(72, "-", "Safari Mesh", {Weapon::AK47, Weapon::AWP, Weapon::G3SG1}),
		PaintKit(73, "-", "Wings", {Weapon::AUG}),
		PaintKit(74, "-", "Polar Camo", {Weapon::G3SG1}),
		PaintKit(75, "-", "Blizzard Marbleized", {Weapon::M249}),
		PaintKit(76, "-", "Winter Forest", {Weapon::Galil}),
		PaintKit(77, "-", "Boreal Forest", {Weapon::P250, Weapon::M4A1S}),
		PaintKit(78, "-", "Forest Night", {Weapon::P250, Weapon::FiveSeven}),
		PaintKit(83, "-", "Orange DDPAT", {Weapon::SawedOff, Weapon::Galil}),
		PaintKit(84, "-", "Pink DDPAT", {Weapon::AWP}),
		PaintKit(90, "-", "Mudder", {Weapon::DesertEagle, Weapon::UMP45}),
		PaintKit(92, "-", "Cyanospatter", {Weapon::FAMAS}),
		PaintKit(93, "-", "Caramel", {Weapon::UMP45}),
		PaintKit(95, "-", "Grassland", {Weapon::P2000, Weapon::XM1014}),
		PaintKit(96, "-", "Blue Spruce", {Weapon::XM1014, Weapon::SSG08}),
		PaintKit(98, "-", "Ultraviolet", {Weapon::MAC10, Weapon::SG553}),
		PaintKit(99, "-", "Sand Dune", {Weapon::P250, Weapon::Nova, Weapon::MAG7, Weapon::SSG08}),
		PaintKit(100, "-", "Storm", {Weapon::MAG7, Weapon::MP9, Weapon::P90, Weapon::AUG, Weapon::SCAR20}),
		PaintKit(101, "-", "Tornado", {Weapon::MAC10, Weapon::Galil, Weapon::M4A4, Weapon::SG553}),
		PaintKit(102, "-", "Whiteout", {Weapon::P250, Weapon::MP7}),
		PaintKit(104, "-", "Grassland Leaves", {Weapon::P2000}),
		PaintKit(107, "-", "Polar Mesh", {Weapon::Nova}),
		PaintKit(110, "-", "Condemned", {Weapon::AUG}),
		PaintKit(111, "-", "Glacier Mesh", {Weapon::P90}),
		PaintKit(116, "-", "Sand Mesh", {Weapon::SCAR20}),
		PaintKit(119, "-", "Sage Spray", {Weapon::SawedOff, Weapon::Galil}),
		PaintKit(122, "-", "Jungle Spray", {Weapon::AK47}),
		PaintKit(124, "-", "Sand Spray", {Weapon::P90}),
		PaintKit(125, "-", "X-Ray", {Weapon::P250}),
		PaintKit(135, "-", "Urban Perforated", {Weapon::XM1014}),
		PaintKit(136, "-", "Waves Perforated", {Weapon::SG553}),
		PaintKit(141, "-", "Orange Peel", {Weapon::FiveSeven, Weapon::MP9, Weapon::MP7}),
		PaintKit(147, "-", "Jungle Dashed", {Weapon::CZ75, Weapon::SSG08, Weapon::G3SG1}),
		PaintKit(148, "-", "Sand Dashed", {Weapon::MP9, Weapon::PPBizon}),
		PaintKit(149, "-", "Urban Dashed", {Weapon::PPBizon}),
		PaintKit(151, "-", "Jungle", {Weapon::FiveSeven, Weapon::M249}),
		PaintKit(153, "-", "Demolition", {Weapon::DualBerettas}),
		PaintKit(154, "-", "Afterimage", {Weapon::FAMAS}),
		PaintKit(155, "-", "Bullet Rain", {Weapon::M4A4}),
		PaintKit(156, "-", "Death by Kitty", {Weapon::P90}),
		PaintKit(157, "-", "Palm", {Weapon::MAC10, Weapon::SCAR20}),
		PaintKit(158, "-", "Walnut", {Weapon::Nova}),
		PaintKit(159, "-", "Brass", {Weapon::Glock18, Weapon::Tec9, Weapon::PPBizon, Weapon::SCAR20}),
		PaintKit(162, "-", "Splash", {Weapon::P250}),
		PaintKit(164, "-", "Modern Hunter", {Weapon::P250, Weapon::Nova, Weapon::PPBizon, Weapon::M4A4}),
		PaintKit(165, "-", "Splash Jam", {Weapon::SCAR20}),
		PaintKit(166, "-", "Blaze Orange", {Weapon::Nova, Weapon::XM1014}),
		PaintKit(167, "-", "Radiation Hazard", {Weapon::M4A4}),
		PaintKit(168, "-", "Nuclear Threat", {Weapon::P250}),
		PaintKit(169, "-", "Fallout Warning", {Weapon::XM1014, Weapon::UMP45, Weapon::P90}),
		PaintKit(170, "-", "Predator", {Weapon::Nova, Weapon::M249, Weapon::AK47}),
		PaintKit(171, "-", "Irradiated Alert", {Weapon::SawedOff, Weapon::MAG7, Weapon::PPBizon}),
		PaintKit(172, "-", "Black Laminate", {Weapon::AK47}),
		PaintKit(174, "-", "BOOM", {Weapon::AWP}),
		PaintKit(175, "-", "Scorched", {Weapon::MP7, Weapon::UMP45, Weapon::P90}),
		PaintKit(176, "-", "Faded Zebra", {Weapon::M4A4}),
		PaintKit(177, "-", "Memento", {Weapon::MAG7}),
		PaintKit(178, "-", "Doomkitty", {Weapon::FAMAS}),
		PaintKit(179, "-", "Nuclear Threat", {Weapon::Tec9}),
		PaintKit(180, "-", "Fire Serpent", {Weapon::AK47}),
		PaintKit(181, "-", "Corticera", {Weapon::AWP}),
		PaintKit(182, "-", "Emerald Dragon", {Weapon::P90}),
		PaintKit(183, "-", "Overgrowth", {Weapon::USPS}),
		PaintKit(184, "-", "Corticera", {Weapon::P2000}),
		PaintKit(185, "-", "Golden Koi", {Weapon::DesertEagle}),
		PaintKit(186, "-", "Wave Spray", {Weapon::SG553}),
		PaintKit(187, "-", "Zirka", {Weapon::M4A4}),
		PaintKit(188, "-", "Graven", {Weapon::MAC10}),
		PaintKit(189, "-", "Bright Water", {Weapon::M4A1S}),
		PaintKit(190, "-", "Black Limba", {Weapon::DualBerettas}),
		PaintKit(191, "-", "Tempest", {Weapon::Nova}),
		PaintKit(192, "-", "Shattered", {Weapon::Galil}),
		PaintKit(193, "-", "Bone Pile", {Weapon::UMP45}),
		PaintKit(194, "-", "Spitfire", {Weapon::FAMAS}),
		PaintKit(195, "-", "Demeter", {Weapon::G3SG1}),
		PaintKit(196, "-", "Emerald", {Weapon::SCAR20}),
		PaintKit(197, "-", "Anodized Navy", {Weapon::AUG}),
		PaintKit(198, "-", "Hazard", {Weapon::MAG7}),
		PaintKit(199, "-", "Dry Season", {Weapon::MP9}),
		PaintKit(200, "-", "Mayan Dreams", {Weapon::SSG08}),
		PaintKit(201, "-", "Palm", {Weapon::Negev}),
		PaintKit(202, "-", "Jungle DDPAT", {Weapon::M249}),
		PaintKit(203, "-", "Rust Coat", {Weapon::PPBizon}),
		PaintKit(204, "-", "Mosaico", {Weapon::SawedOff}),
		PaintKit(205, "-", "Jungle", {Weapon::XM1014}),
		PaintKit(206, "-", "Tornado", {Weapon::Tec9}),
		PaintKit(207, "-", "Facets", {Weapon::P250}),
		PaintKit(208, "-", "Sand Dune", {Weapon::Glock18}),
		PaintKit(209, "-", "Groundwater", {Weapon::MP7}),
		PaintKit(210, "-", "Anodized Gunmetal", {Weapon::FiveSeven}),
		PaintKit(211, "-", "Ocean Foam", {Weapon::P2000}),
		PaintKit(212, "-", "Graphite", {Weapon::AWP}),
		PaintKit(213, "-", "Ocean Foam", {Weapon::MP7}),
		PaintKit(214, "-", "Graphite", {Weapon::Nova}),
		PaintKit(215, "-", "X-Ray", {Weapon::M4A4}),
		PaintKit(216, "-", "Blue Titanium", {Weapon::Tec9, Weapon::Galil}),
		PaintKit(217, "-", "Blood Tiger", {Weapon::USPS, Weapon::M4A1S}),
		PaintKit(218, "-", "Hexane", {Weapon::CZ75, Weapon::FAMAS}),
		PaintKit(219, "-", "Hive", {Weapon::P250}),
		PaintKit(220, "-", "Hemoglobin", {Weapon::DualBerettas}),
		PaintKit(221, "-", "Serum", {Weapon::USPS}),
		PaintKit(222, "-", "Blood in the Water", {Weapon::SSG08}),
		PaintKit(223, "-", "Nightshade", {Weapon::FiveSeven}),
		PaintKit(224, "-", "Water Sigil", {Weapon::PPBizon}),
		PaintKit(225, "-", "Ghost Camo", {Weapon::Nova}),
		PaintKit(226, "-", "Blue Laminate", {Weapon::AK47}),
		PaintKit(227, "-", "Electric Hive", {Weapon::AWP}),
		PaintKit(228, "-", "Blind Spot", {Weapon::P90}),
		PaintKit(229, "-", "Azure Zebra", {Weapon::G3SG1}),
		PaintKit(230, "-", "Steel Disruption", {Weapon::Glock18, Weapon::P250}),
		PaintKit(231, "-", "Cobalt Disruption", {Weapon::DesertEagle}),
		PaintKit(232, "-", "Crimson Web", {Weapon::DesertEagle, Weapon::SCAR20}),
		PaintKit(233, "-", "Tropical Storm", {Weapon::SSG08}),
		PaintKit(234, "-", "Ash Wood", {Weapon::P90}),
		PaintKit(235, "-", "VariCamo", {Weapon::Tec9, Weapon::Galil, Weapon::M4A1S, Weapon::G3SG1}),
		PaintKit(236, "-", "Night Ops", {Weapon::USPS, Weapon::PPBizon}),
		PaintKit(237, "-", "Urban Rubble", {Weapon::DesertEagle, Weapon::Galil}),
		PaintKit(238, "-", "VariCamo Blue", {Weapon::XM1014}),
		PaintKit(240, "-", "CaliCamo", {Weapon::XM1014, Weapon::Negev}),
		PaintKit(241, "-", "Hunting Blind", {Weapon::Galil}),
		PaintKit(242, "-", "Army Mesh", {Weapon::Tec9}),
		PaintKit(243, "-", "Gator Mesh", {Weapon::M249, Weapon::SG553}),
		PaintKit(244, "-", "Teardown", {Weapon::P90, Weapon::FAMAS}),
		PaintKit(245, "-", "Army Recon", {Weapon::MP7}),
		PaintKit(246, "-", "Amber Fade", {Weapon::P2000, Weapon::SawedOff, Weapon::MAC10}),
		PaintKit(247, "-", "Damascus Steel", {Weapon::SG553}),
		PaintKit(248, "-", "Red Quartz", {Weapon::Tec9}),
		PaintKit(249, "-", "Cobalt Quartz", {Weapon::DualBerettas}),
		PaintKit(250, "-", "Full Stop", {Weapon::SawedOff, Weapon::MP7}),
		PaintKit(251, "-", "Pit Viper", {Weapon::AWP}),
		PaintKit(252, "-", "Silver Quartz", {Weapon::FiveSeven}),
		PaintKit(253, "-", "Acid Fade", {Weapon::SSG08}),
		PaintKit(254, "-", "Nitro", {Weapon::FiveSeven, Weapon::M4A1S}),
		PaintKit(255, "-", "Asiimov", {Weapon::M4A4}),
		PaintKit(256, "-", "The Kraken", {Weapon::SawedOff}),
		PaintKit(257, "-", "Guardian", {Weapon::M4A1S}),
		PaintKit(258, "-", "Mehndi", {Weapon::P250}),
		PaintKit(259, "-", "Redline", {Weapon::AWP}),
		PaintKit(260, "-", "Pulse", {Weapon::FAMAS}),
		PaintKit(261, "-", "Marina", {Weapon::DualBerettas}),
		PaintKit(262, "-", "Rose Iron", {Weapon::MP9}),
		PaintKit(263, "-", "Rising Skull", {Weapon::Nova}),
		PaintKit(264, "-", "Sandstorm", {Weapon::Galil}),
		PaintKit(265, "-", "Kami", {Weapon::FiveSeven}),
		PaintKit(266, "-", "Magma", {Weapon::M249}),
		PaintKit(267, "-", "Cobalt Halftone", {Weapon::PPBizon}),
		PaintKit(268, "-", "Tread Plate", {Weapon::CZ75}),
		PaintKit(269, "-", "The Fuschia Is Now", {Weapon::CZ75}),
		PaintKit(270, "-", "Victoria", {Weapon::CZ75}),
		PaintKit(271, "-", "Undertow", {Weapon::P250}),
		PaintKit(272, "-", "Titanium Bit", {Weapon::Tec9}),
		PaintKit(273, "-", "Heirloom", {Weapon::DesertEagle}),
		PaintKit(274, "-", "Copper Galaxy", {Weapon::FiveSeven}),
		PaintKit(275, "-", "Red FragCam", {Weapon::P2000}),
		PaintKit(276, "-", "Panther", {Weapon::DualBerettas}),
		PaintKit(277, "-", "Stainless", {Weapon::USPS}),
		PaintKit(278, "-", "Blue Fissure", {Weapon::Glock18}),
		PaintKit(279, "-", "Asiimov", {Weapon::AWP}),
		PaintKit(280, "-", "Chameleon", {Weapon::AUG}),
		PaintKit(281, "-", "Corporal", {Weapon::UMP45}),
		PaintKit(282, "-", "Redline", {Weapon::AK47}),
		PaintKit(283, "-", "Trigon", {Weapon::P90}),
		PaintKit(284, "-", "Heat", {Weapon::MAC10}),
		PaintKit(285, "-", "Terrain", {Weapon::Negev}),
		PaintKit(286, "-", "Antique", {Weapon::Nova}),
		PaintKit(287, "-", "Pulse", {Weapon::SG553}),
		PaintKit(288, "-", "Sergeant", {Weapon::FAMAS}),
		PaintKit(289, "-", "Sandstorm", {Weapon::Tec9}),
		PaintKit(290, "-", "Guardian", {Weapon::USPS}),
		PaintKit(291, "-", "Heaven Guard", {Weapon::MAG7}),
		PaintKit(293, "-", "Death Rattle", {Weapon::Glock18, Weapon::PPBizon}),
		PaintKit(294, "-", "Green Apple", {Weapon::Nova, Weapon::G3SG1}),
		PaintKit(295, "-", "Franklin", {Weapon::P250}),
		PaintKit(296, "-", "Meteorite", {Weapon::DesertEagle}),
		PaintKit(297, "-", "Tuxedo", {Weapon::CZ75, Weapon::Galil}),
		PaintKit(298, "-", "Army Sheen", {Weapon::CZ75, Weapon::Nova, Weapon::Negev, Weapon::MP9, Weapon::SG553, Weapon::SCAR20}),
		PaintKit(299, "-", "Caged Steel", {Weapon::Nova}),
		PaintKit(300, "-", "Emerald Pinstripe", {Weapon::AK47}),
		PaintKit(301, "-", "Atomic Alloy", {Weapon::M4A1S}),
		PaintKit(302, "-", "Vulcan", {Weapon::AK47}),
		PaintKit(303, "-", "Isaac", {Weapon::Tec9}),
		PaintKit(304, "-", "Slashed", {Weapon::SSG08}),
		PaintKit(305, "-", "Torque", {Weapon::AUG}),
		PaintKit(306, "-", "Antique", {Weapon::PPBizon}),
		PaintKit(307, "-", "Retribution", {Weapon::DualBerettas}),
		PaintKit(308, "-", "Kami", {Weapon::Galil}),
		PaintKit(309, "-", "Howl", {Weapon::M4A4}),
		PaintKit(310, "-", "Curse", {Weapon::MAC10}),
		PaintKit(311, "-", "Desert Warfare", {Weapon::P90}),
		PaintKit(312, "-", "Cyrex", {Weapon::SCAR20}),
		PaintKit(313, "-", "Orion", {Weapon::USPS}),
		PaintKit(314, "-", "Heaven Guard", {Weapon::XM1014}),
		PaintKit(315, "-", "Poison Dart", {Weapon::CZ75}),
		PaintKit(316, "-", "Jaguar", {Weapon::AK47}),
		PaintKit(317, "-", "Bratatat", {Weapon::Negev}),
		PaintKit(318, "-", "Road Rash", {Weapon::USPS}),
		PaintKit(319, "-", "Detour", {Weapon::SSG08}),
		PaintKit(320, "-", "Red Python", {Weapon::XM1014}),
		PaintKit(321, "-", "Master Piece", {Weapon::M4A1S}),
		PaintKit(322, "-", "Nitro", {Weapon::CZ75}),
		PaintKit(323, "-", "Rust Coat", {Weapon::Nova, Weapon::SawedOff}),
		PaintKit(325, "-", "Chalice", {Weapon::CZ75}),
		PaintKit(326, "-", "Knight", {Weapon::M4A1S}),
		PaintKit(327, "-", "Chainmail", {Weapon::P2000, Weapon::MAG7}),
		PaintKit(328, "-", "Hand Cannon", {Weapon::DesertEagle}),
		PaintKit(329, "-", "Dark Age", {Weapon::MP9}),
		PaintKit(330, "-", "Briar", {Weapon::DualBerettas}),
		PaintKit(332, "-", "Royal Blue", {Weapon::USPS}),
		PaintKit(333, "-", "Indigo", {Weapon::CZ75, Weapon::MAC10, Weapon::UMP45}),
		PaintKit(334, "-", "Twist", {Weapon::CZ75}),
		PaintKit(335, "-", "Module", {Weapon::P90}),
		PaintKit(336, "-", "Desert-Strike", {Weapon::M4A4}),
		PaintKit(337, "-", "Tatter", {Weapon::MAC10}),
		PaintKit(338, "-", "Pulse", {Weapon::P2000}),
		PaintKit(339, "-", "Caiman", {Weapon::USPS}),
		PaintKit(340, "-", "Jet Set", {Weapon::AK47}),
		PaintKit(341, "-", "First Class", {Weapon::AK47}),
		PaintKit(342, "-", "Leather", {Weapon::P90}),
		PaintKit(343, "-", "Commuter", {Weapon::MAC10}),
		PaintKit(344, "-", "Dragon Lore", {Weapon::AWP}),
		PaintKit(345, "-", "First Class", {Weapon::SawedOff}),
		PaintKit(346, "-", "Coach Class", {Weapon::P2000}),
		PaintKit(347, "-", "Pilot", {Weapon::DesertEagle}),
		PaintKit(348, "-", "Red Leather", {Weapon::XM1014}),
		PaintKit(349, "-", "Osiris", {Weapon::PPBizon}),
		PaintKit(350, "-", "Tigris", {Weapon::CZ75}),
		PaintKit(351, "-", "Conspiracy", {Weapon::DesertEagle}),
		PaintKit(352, "-", "Fowl Play", {Weapon::FiveSeven}),
		PaintKit(353, "-", "Water Elemental", {Weapon::Glock18}),
		PaintKit(354, "-", "Urban Hazard", {Weapon::MP7}),
		PaintKit(355, "-", "Desert-Strike", {Weapon::Negev}),
		PaintKit(356, "-", "Koi", {Weapon::Nova}),
		PaintKit(357, "-", "Ivory", {Weapon::P2000}),
		PaintKit(358, "-", "Supernova", {Weapon::P250}),
		PaintKit(359, "-", "Asiimov", {Weapon::P90}),
		PaintKit(360, "-", "Cyrex", {Weapon::M4A1S}),
		PaintKit(361, "-", "Abyss", {Weapon::SSG08}),
		PaintKit(362, "-", "Labyrinth", {Weapon::UMP45}),
		PaintKit(363, "-", "Traveler", {Weapon::SG553}),
		PaintKit(364, "-", "Business Class", {Weapon::USPS}),
		PaintKit(365, "-", "Olive Plaid", {Weapon::MP7}),
		PaintKit(366, "-", "Green Plaid", {Weapon::CZ75, Weapon::MP9}),
		PaintKit(367, "-", "Reactor", {Weapon::Glock18}),
		PaintKit(368, "-", "Setting Sun", {Weapon::MP9}),
		PaintKit(369, "-", "Nuclear Waste", {Weapon::Negev}),
		PaintKit(370, "-", "Bone Machine", {Weapon::XM1014}),
		PaintKit(371, "-", "Styx", {Weapon::FAMAS}),
		PaintKit(372, "-", "Nuclear Garden", {Weapon::MAC10}),
		PaintKit(373, "-", "Contamination", {Weapon::P250}),
		PaintKit(374, "-", "Toxic", {Weapon::Tec9}),
		PaintKit(375, "-", "Radiation Hazard", {Weapon::AUG}),
		PaintKit(376, "-", "Chemical Green", {Weapon::PPBizon}),
		PaintKit(377, "-", "Hot Shot", {Weapon::FiveSeven}),
		PaintKit(378, "-", "Fallout Warning", {Weapon::SG553}),
		PaintKit(379, "-", "Cerberus", {Weapon::Galil}),
		PaintKit(380, "-", "Wasteland Rebel", {Weapon::AK47}),
		PaintKit(381, "-", "Grinder", {Weapon::Glock18}),
		PaintKit(382, "-", "Murky", {Weapon::G3SG1}),
		PaintKit(383, "-", "Basilisk", {Weapon::M4A1S}),
		PaintKit(384, "-", "Griffin", {Weapon::M4A4}),
		PaintKit(385, "-", "Firestarter", {Weapon::MAG7}),
		PaintKit(386, "-", "Dart", {Weapon::MP9}),
		PaintKit(387, "-", "Urban Hazard", {Weapon::FiveSeven}),
		PaintKit(388, "-", "Cartel", {Weapon::P250}),
		PaintKit(389, "-", "Fire Elemental", {Weapon::P2000}),
		PaintKit(390, "-", "Highwayman", {Weapon::SawedOff}),
		PaintKit(391, "-", "Cardiac", {Weapon::SCAR20}),
		PaintKit(392, "-", "Delusion", {Weapon::UMP45}),
		PaintKit(393, "-", "Tranquility", {Weapon::XM1014}),
		PaintKit(394, "-", "Cartel", {Weapon::AK47}),
		PaintKit(395, "-", "Man-o'-war", {Weapon::AWP}),
		PaintKit(396, "-", "Urban Shock", {Weapon::DualBerettas}),
		PaintKit(397, "-", "Naga", {Weapon::DesertEagle}),
		PaintKit(398, "-", "Chatterbox", {Weapon::Galil}),
		PaintKit(399, "-", "Catacombs", {Weapon::Glock18}),
		PaintKit(400, "-", "Dragon King", {Weapon::M4A4}),
		PaintKit(401, "-", "System Lock", {Weapon::M249}),
		PaintKit(402, "-", "Malachite", {Weapon::MAC10}),
		PaintKit(403, "-", "Deadly Poison", {Weapon::MP9}),
		PaintKit(404, "-", "Muertos", {Weapon::P250}),
		PaintKit(405, "-", "Serenity", {Weapon::SawedOff}),
		PaintKit(406, "-", "Grotto", {Weapon::SCAR20}),
		PaintKit(407, "-", "Quicksilver", {Weapon::XM1014}),
		PaintKit(422, "-", "Elite Build", {Weapon::AK47}),
		PaintKit(423, "-", "Armor Core", {Weapon::MP7}),
		PaintKit(424, "-", "Worm God", {Weapon::AWP}),
		PaintKit(425, "-", "Bronze Deco", {Weapon::DesertEagle}),
		PaintKit(426, "-", "Valence", {Weapon::P250}),
		PaintKit(427, "-", "Monkey Business", {Weapon::FiveSeven}),
		PaintKit(428, "-", "Eco", {Weapon::Galil}),
		PaintKit(429, "-", "Djinn", {Weapon::FAMAS}),
		PaintKit(430, "-", "Hyper Beast", {Weapon::M4A1S}),
		PaintKit(431, "-", "Heat", {Weapon::MAG7}),
		PaintKit(432, "-", "Man-o'-war", {Weapon::Negev}),
		PaintKit(433, "-", "Neon Rider", {Weapon::MAC10}),
		PaintKit(434, "-", "Origami", {Weapon::SawedOff}),
		PaintKit(435, "-", "Pole Position", {Weapon::CZ75}),
		PaintKit(436, "-", "Grand Prix", {Weapon::UMP45}),
		PaintKit(437, "-", "Twilight Galaxy", {Weapon::Glock18}),
		PaintKit(438, "-", "Chronos", {Weapon::G3SG1}),
		PaintKit(439, "-", "Hades", {Weapon::Tec9}),
		PaintKit(440, "-", "Icarus Fell", {Weapon::M4A1S}),
		PaintKit(441, "-", "Minotaur's Labyrinth", {Weapon::UMP45}),
		PaintKit(442, "-", "Asterion", {Weapon::MP7}),
		PaintKit(443, "-", "Pathfinder", {Weapon::P2000, Weapon::USPS}),
		PaintKit(444, "-", "Daedalus", {Weapon::AUG}),
		PaintKit(445, "-", "Hot Rod", {Weapon::M4A1S}),
		PaintKit(446, "-", "Medusa", {Weapon::AWP}),
		PaintKit(447, "-", "Duelist", {Weapon::DualBerettas}),
		PaintKit(448, "-", "Pandora's Box", {Weapon::MP9}),
		PaintKit(449, "-", "Poseidon", {Weapon::M4A4}),
		PaintKit(450, "-", "Moon in Libra", {Weapon::DualBerettas, Weapon::Nova}),
		PaintKit(451, "-", "Sun in Leo", {Weapon::AWP}),
		PaintKit(452, "-", "Shipping Forecast", {Weapon::M249}),
		PaintKit(453, "-", "Emerald", {Weapon::DualBerettas, Weapon::CZ75}),
		PaintKit(454, "-", "Para Green", {Weapon::USPS}),
		PaintKit(455, "-", "Akihabara Accept", {Weapon::AUG}),
		PaintKit(456, "-", "Hydroponic", {Weapon::AK47}),
		PaintKit(457, "-", "Bamboo Print", {Weapon::PPBizon}),
		PaintKit(458, "-", "Bamboo Shadow", {Weapon::SawedOff}),
		PaintKit(459, "-", "Bamboo Forest", {Weapon::Tec9}),
		PaintKit(460, "-", "Aqua Terrace", {Weapon::Galil}),
		PaintKit(462, "-", "Counter Terrace", {Weapon::MAG7}),
		PaintKit(463, "-", "Terrace", {Weapon::Tec9}),
		PaintKit(464, "-", "Neon Kimono", {Weapon::FiveSeven}),
		PaintKit(465, "-", "Orange Kimono", {Weapon::G3SG1}),
		PaintKit(466, "-", "Crimson Kimono", {Weapon::P250}),
		PaintKit(467, "-", "Mint Kimono", {Weapon::P250}),
		PaintKit(468, "-", "Midnight Storm", {Weapon::DesertEagle}),
		PaintKit(469, "-", "Sunset Storm 1", {Weapon::DesertEagle}),
		PaintKit(470, "-", "Sunset Storm 2", {Weapon::DesertEagle}),
		PaintKit(471, "-", "Daybreak", {Weapon::M4A4}),
		PaintKit(472, "-", "Impact Drill", {Weapon::M249}),
		PaintKit(473, "-", "Seabird", {Weapon::MAG7}),
		PaintKit(474, "-", "Aquamarine Revenge", {Weapon::AK47}),
		PaintKit(475, "-", "Hyper Beast", {Weapon::AWP}),
		PaintKit(476, "-", "Yellow Jacket", {Weapon::CZ75}),
		PaintKit(477, "-", "Neural Net", {Weapon::FAMAS}),
		PaintKit(478, "-", "Rocket Pop", {Weapon::Galil}),
		PaintKit(479, "-", "Bunsen Burner", {Weapon::Glock18}),
		PaintKit(480, "-", "Evil Daimyo", {Weapon::M4A4}),
		PaintKit(481, "-", "Nemesis", {Weapon::MP7}),
		PaintKit(482, "-", "Ruby Poison Dart", {Weapon::MP9}),
		PaintKit(483, "-", "Loudmouth", {Weapon::Negev}),
		PaintKit(484, "-", "Ranger", {Weapon::Nova}),
		PaintKit(485, "-", "Handgun", {Weapon::P2000}),
		PaintKit(486, "-", "Elite Build", {Weapon::P90}),
		PaintKit(487, "-", "Cyrex", {Weapon::SG553}),
		PaintKit(488, "-", "Riot", {Weapon::UMP45}),
		PaintKit(489, "-", "Torque", {Weapon::USPS}),
		PaintKit(490, "-", "Frontside Misty", {Weapon::AK47}),
		PaintKit(491, "-", "Dualing Dragons", {Weapon::DualBerettas}),
		PaintKit(492, "-", "Survivor Z", {Weapon::FAMAS}),
		PaintKit(493, "-", "Flux", {Weapon::G3SG1}),
		PaintKit(494, "-", "Stone Cold", {Weapon::Galil}),
		PaintKit(495, "-", "Wraiths", {Weapon::Glock18}),
		PaintKit(496, "-", "Nebula Crusader", {Weapon::M249}),
		PaintKit(497, "-", "Golden Coil", {Weapon::M4A1S}),
		PaintKit(498, "-", "Rangeen", {Weapon::MAC10}),
		PaintKit(499, "-", "Cobalt Core", {Weapon::MAG7}),
		PaintKit(500, "-", "Special Delivery", {Weapon::MP7}),
		PaintKit(501, "-", "Wingshot", {Weapon::P250}),
		PaintKit(502, "-", "Green Marine", {Weapon::SCAR20}),
		PaintKit(503, "-", "Big Iron", {Weapon::SSG08}),
		PaintKit(504, "-", "Kill Confirmed", {Weapon::USPS}),
		PaintKit(505, "-", "Scumbria", {Weapon::XM1014}),
		PaintKit(506, "-", "Point Disarray", {Weapon::AK47}),
		PaintKit(507, "-", "Ricochet", {Weapon::AUG}),
		PaintKit(508, "-", "Fuel Rod", {Weapon::PPBizon}),
		PaintKit(509, "-", "Corinthian", {Weapon::DesertEagle}),
		PaintKit(510, "-", "Retrobution", {Weapon::FiveSeven}),
		PaintKit(511, "-", "The Executioner", {Weapon::G3SG1}),
		PaintKit(512, "-", "Royal Paladin", {Weapon::M4A4}),
		PaintKit(514, "-", "Power Loader", {Weapon::Negev}),
		PaintKit(515, "-", "Imperial", {Weapon::P2000}),
		PaintKit(516, "-", "Shapewood", {Weapon::P90}),
		PaintKit(517, "-", "Yorick", {Weapon::SawedOff}),
		PaintKit(518, "-", "Outbreak", {Weapon::SCAR20}),
		PaintKit(519, "-", "Tiger Moth", {Weapon::SG553}),
		PaintKit(520, "-", "Avalanche", {Weapon::Tec9}),
		PaintKit(521, "-", "Teclu Burner", {Weapon::XM1014}),
		PaintKit(522, "-", "Fade", {Weapon::R8Revolver}),
		PaintKit(523, "-", "Amber Fade", {Weapon::R8Revolver}),
		PaintKit(524, "-", "Fuel Injector", {Weapon::AK47}),
		PaintKit(525, "-", "Elite Build", {Weapon::AWP}),
		PaintKit(526, "-", "Photic Zone", {Weapon::PPBizon}),
		PaintKit(527, "-", "Kumicho Dragon", {Weapon::DesertEagle}),
		PaintKit(528, "-", "Cartel", {Weapon::DualBerettas}),
		PaintKit(529, "-", "Valence", {Weapon::FAMAS}),
		PaintKit(530, "-", "Triumvirate", {Weapon::FiveSeven}),
		PaintKit(532, "-", "Royal Legion", {Weapon::Glock18}),
		PaintKit(533, "-", "The Battlestar", {Weapon::M4A4}),
		PaintKit(534, "-", "Lapis Gator", {Weapon::MAC10}),
		PaintKit(535, "-", "Praetorian", {Weapon::MAG7}),
		PaintKit(536, "-", "Impire", {Weapon::MP7}),
		PaintKit(537, "-", "Hyper Beast", {Weapon::Nova}),
		PaintKit(538, "-", "Necropos", {Weapon::SSG08}),
		PaintKit(539, "-", "Jambiya", {Weapon::Tec9}),
		PaintKit(540, "-", "Lead Conduit", {Weapon::USPS}),
		PaintKit(541, "-", "Fleet Flock", {Weapon::AUG}),
		PaintKit(542, "-", "Judgement of Anubis", {Weapon::PPBizon}),
		PaintKit(543, "-", "Red Astor", {Weapon::CZ75}),
		PaintKit(544, "-", "Ventilators", {Weapon::DualBerettas}),
		PaintKit(545, "-", "Orange Crash", {Weapon::G3SG1}),
		PaintKit(546, "-", "Firefight", {Weapon::Galil}),
		PaintKit(547, "-", "Spectre", {Weapon::M249}),
		PaintKit(548, "-", "Chantico's Fire", {Weapon::M4A1S}),
		PaintKit(549, "-", "Bioleak", {Weapon::MP9}),
		PaintKit(550, "-", "Oceanic", {Weapon::P2000}),
		PaintKit(551, "-", "Asiimov", {Weapon::P250}),
		PaintKit(552, "-", "Fubar", {Weapon::SawedOff}),
		PaintKit(553, "-", "Atlas", {Weapon::SG553}),
		PaintKit(554, "-", "Ghost Crusader", {Weapon::SSG08}),
		PaintKit(555, "-", "Re-Entry", {Weapon::Tec9}),
		PaintKit(556, "-", "Primal Saber", {Weapon::UMP45}),
		PaintKit(557, "-", "Black Tie", {Weapon::XM1014}),
		PaintKit(583, "-", "Aristocrat", {Weapon::AUG}),
		PaintKit(584, "-", "Phobos", {Weapon::AWP}),
		PaintKit(585, "-", "Violent Daimyo", {Weapon::FiveSeven}),
		PaintKit(586, "-", "Wasteland Rebel", {Weapon::Glock18}),
		PaintKit(587, "-", "Mecha Industries", {Weapon::M4A1S}),
		PaintKit(588, "-", "Desolate Space", {Weapon::M4A4}),
		PaintKit(589, "-", "Carnivore", {Weapon::MAC10}),
		PaintKit(590, "-", "Exo", {Weapon::Nova}),
		PaintKit(591, "-", "Imperial Dragon", {Weapon::P2000}),
		PaintKit(592, "-", "Iron Clad", {Weapon::P250}),
		PaintKit(593, "-", "Chopper", {Weapon::P90}),
		PaintKit(594, "-", "Harvester", {Weapon::PPBizon}),
		PaintKit(595, "-", "Reboot", {Weapon::R8Revolver}),
		PaintKit(596, "-", "Limelight", {Weapon::SawedOff}),
		PaintKit(597, "-", "Bloodsport", {Weapon::SCAR20}),
		PaintKit(598, "-", "Aerial", {Weapon::SG553}),
		PaintKit(599, "-", "Ice Cap", {Weapon::Tec9}),
		PaintKit(600, "-", "Neon Revolution", {Weapon::AK47}),
		PaintKit(601, "-", "Syd Mead", {Weapon::AUG}),
		PaintKit(602, "-", "Imprint", {Weapon::CZ75}),
		PaintKit(603, "-", "Directive", {Weapon::DesertEagle}),
		PaintKit(604, "-", "Roll Cage", {Weapon::FAMAS}),
		PaintKit(605, "-", "Scumbria", {Weapon::FiveSeven}),
		PaintKit(606, "-", "Ventilator", {Weapon::G3SG1}),
		PaintKit(607, "-", "Weasel", {Weapon::Glock18}),
		PaintKit(608, "-", "Petroglyph", {Weapon::MAG7}),
		PaintKit(609, "-", "Airlock", {Weapon::MP9}),
		PaintKit(610, "-", "Dazzle", {Weapon::Negev}),
		PaintKit(611, "-", "Grim", {Weapon::P90}),
		PaintKit(612, "-", "Powercore", {Weapon::SCAR20}),
		PaintKit(613, "-", "Triarch", {Weapon::SG553}),
		PaintKit(614, "-", "Fuel Injector", {Weapon::Tec9}),
		PaintKit(615, "-", "Briefing", {Weapon::UMP45}),
		PaintKit(616, "-", "Slipstream", {Weapon::XM1014}),
		PaintKit(622, "-", "Polymer", {Weapon::CZ75}),
		PaintKit(623, "-", "Ironwork", {Weapon::Glock18}),
		PaintKit(624, "-", "Dragonfire", {Weapon::SSG08}),
		PaintKit(625, "-", "Royal Consorts", {Weapon::DualBerettas}),
		PaintKit(626, "-", "Mecha Industries", {Weapon::FAMAS}),
		PaintKit(627, "-", "Cirrus", {Weapon::MP7}),
		PaintKit(628, "-", "Stinger", {Weapon::G3SG1}),
		PaintKit(629, "-", "Black Sand", {Weapon::Galil}),
		PaintKit(630, "-", "Sand Scale", {Weapon::MP9}),
		PaintKit(631, "-", "Flashback", {Weapon::M4A1S}),
		PaintKit(632, "-", "Buzz Kill", {Weapon::M4A4}),
		PaintKit(633, "-", "Sonar", {Weapon::MAG7}),
		PaintKit(634, "-", "Gila", {Weapon::Nova}),
		PaintKit(635, "-", "Turf", {Weapon::P2000}),
		PaintKit(636, "-", "Shallow Grave", {Weapon::P90}),
		PaintKit(637, "-", "Cyrex", {Weapon::USPS}),
		PaintKit(638, "-", "Wasteland Princess", {Weapon::SawedOff}),
		PaintKit(639, "-", "Bloodsport", {Weapon::AK47}),
		PaintKit(640, "-", "Fever Dream", {Weapon::AWP}),
		PaintKit(641, "-", "Jungle Slipstream", {Weapon::PPBizon}),
		PaintKit(642, "-", "Blueprint", {Weapon::SCAR20}),
		PaintKit(643, "-", "Xiangliu", {Weapon::CZ75}),
		PaintKit(644, "-", "Decimator", {Weapon::M4A1S}),
		PaintKit(645, "-", "Oxide Blaze", {Weapon::DesertEagle}),
		PaintKit(646, "-", "Capillary", {Weapon::FiveSeven}),
		PaintKit(647, "-", "Crimson Tsunami", {Weapon::Galil}),
		PaintKit(648, "-", "Emerald Poison Dart", {Weapon::M249}),
		PaintKit(649, "-", "Akoben", {Weapon::MP7}),
		PaintKit(650, "-", "Ripple", {Weapon::P250}),
		PaintKit(651, "-", "Last Dive", {Weapon::MAC10}),
		PaintKit(652, "-", "Scaffold", {Weapon::UMP45}),
		PaintKit(653, "-", "Neo-Noir", {Weapon::USPS}),
		PaintKit(654, "-", "Seasons", {Weapon::XM1014}),
		PaintKit(655, "-", "Zander", {Weapon::SawedOff}),
		PaintKit(656, "-", "Orbit Mk01", {Weapon::AK47}),
		PaintKit(657, "-", "Blueprint", {Weapon::USPS}),
		PaintKit(658, "-", "Cobra Strike", {Weapon::DualBerettas}),
		PaintKit(659, "-", "Macabre", {Weapon::FAMAS}),
		PaintKit(660, "-", "Hyper Beast", {Weapon::FiveSeven}),
		PaintKit(661, "-", "Sugar Rush", {Weapon::Galil}),
		PaintKit(662, "-", "Oni Taiji", {Weapon::AWP}),
		PaintKit(663, "-", "Briefing", {Weapon::M4A1S}),
		PaintKit(664, "-", "Hellfire", {Weapon::M4A4}),
		PaintKit(665, "-", "Aloha", {Weapon::MAC10}),
		PaintKit(666, "-", "Hard Water", {Weapon::MAG7}),
		PaintKit(667, "-", "Woodsman", {Weapon::P2000}),
		PaintKit(668, "-", "Red Rock", {Weapon::P250}),
		PaintKit(669, "-", "Death Grip", {Weapon::P90}),
		PaintKit(670, "-", "Death's Head", {Weapon::SSG08}),
		PaintKit(671, "-", "Cut Out", {Weapon::Tec9}),
		PaintKit(672, "-", "Metal Flowers", {Weapon::UMP45}),
		PaintKit(673, "-", "Morris", {Weapon::SawedOff}),
		PaintKit(674, "-", "Triqua", {Weapon::AUG}),
		PaintKit(675, "-", "The Empress", {Weapon::AK47}),
		PaintKit(676, "-", "High Roller", {Weapon::PPBizon}),
		PaintKit(677, "-", "Hunter", {Weapon::G3SG1}),
		PaintKit(678, "-", "See Ya Later", {Weapon::P250}),
		PaintKit(679, "-", "Goo", {Weapon::MP9}),
		PaintKit(680, "-", "Off World", {Weapon::Glock18}),
		PaintKit(681, "-", "Leaded Glass", {Weapon::M4A1S}),
		PaintKit(682, "-", "Oceanic", {Weapon::MAC10}),
		PaintKit(683, "-", "Llama Cannon", {Weapon::R8Revolver}),
		PaintKit(684, "-", "Cracked Opal", {Weapon::Tec9}),
		PaintKit(685, "-", "Jungle Slipstream", {Weapon::SCAR20}),
		PaintKit(686, "-", "Phantom", {Weapon::SG553}),
		PaintKit(687, "-", "Tacticat", {Weapon::CZ75}),
		PaintKit(688, "-", "Exposure", {Weapon::UMP45}),
		PaintKit(689, "-", "Ziggy", {Weapon::XM1014}),
		PaintKit(690, "-", "Stymphalian", {Weapon::AUG}),
		PaintKit(691, "-", "Mortis", {Weapon::AWP}),
		PaintKit(692, "-", "Night Riot", {Weapon::PPBizon}),
		PaintKit(693, "-", "Flame Test", {Weapon::FiveSeven}),
		PaintKit(694, "-", "Moonrise", {Weapon::Glock18}),
		PaintKit(695, "-", "Neo-Noir", {Weapon::M4A4}),
		PaintKit(696, "-", "Bloodsport", {Weapon::MP7}),
		PaintKit(697, "-", "Black Sand", {Weapon::MP9}),
		PaintKit(698, "-", "Lionfish", {Weapon::Negev}),
		PaintKit(699, "-", "Wild Six", {Weapon::Nova}),
		PaintKit(700, "-", "Urban Hazard", {Weapon::P2000}),
		PaintKit(701, "-", "Grip", {Weapon::R8Revolver}),
		PaintKit(702, "-", "Aloha", {Weapon::SG553}),
		PaintKit(703, "-", "SWAG-7", {Weapon::MAG7}),
		PaintKit(704, "-", "Arctic Wolf", {Weapon::UMP45}),
		PaintKit(705, "-", "Cortex", {Weapon::USPS}),
		PaintKit(706, "-", "Oxide Blaze", {Weapon::XM1014}),
		PaintKit(707, "-", "Neon Rider", {Weapon::AK47}),
		PaintKit(708, "-", "Amber Slipstream", {Weapon::AUG}),
		PaintKit(709, "-", "Eco", {Weapon::CZ75}),
		PaintKit(710, "-", "Shred", {Weapon::DualBerettas}),
		PaintKit(711, "-", "Code Red", {Weapon::DesertEagle}),
		PaintKit(712, "-", "High Seas", {Weapon::G3SG1}),
		PaintKit(713, "-", "Warhawk", {Weapon::Glock18}),
		PaintKit(714, "-", "Nightmare", {Weapon::M4A1S}),
		PaintKit(715, "-", "Capillary", {Weapon::MP9}),
		PaintKit(716, "-", "Toy Soldier", {Weapon::Nova}),
		PaintKit(717, "-", "Traction", {Weapon::P90}),
		PaintKit(718, "-", "PAW", {Weapon::AWP}),
		PaintKit(719, "-", "Powercore", {Weapon::MP7}),
		PaintKit(720, "-", "Devourer", {Weapon::SawedOff}),
		PaintKit(721, "-", "Survivalist", {Weapon::R8Revolver}),
		PaintKit(722, "-", "Snek-9", {Weapon::Tec9}),
		PaintKit(723, "-", "Eye of Athena", {Weapon::FAMAS}),
		PaintKit(724, "-", "Wild Lotus", {Weapon::AK47}),
		PaintKit(725, "-", "Day Lily", {Weapon::UMP45}),
		PaintKit(726, "-", "Sunset Lily", {Weapon::P90}),
		PaintKit(727, "-", "Midnight Lily", {Weapon::AUG}),
		PaintKit(728, "-", "Teal Blossom", {Weapon::MP7}),
		PaintKit(729, "-", "Crimson Blossom", {Weapon::FiveSeven}),
		PaintKit(730, "-", "Dark Blossom", {Weapon::M4A4}),
		PaintKit(731, "-", "Banana Leaf", {Weapon::XM1014}),
		PaintKit(732, "-", "Synth Leaf", {Weapon::Glock18}),
		PaintKit(733, "-", "Rust Leaf", {Weapon::Tec9}),
		PaintKit(734, "-", "Wild Lily", {Weapon::MP9}),
		PaintKit(736, "-", "The Prince", {Weapon::AWP}),
		PaintKit(737, "-", "Cinquedea", {Weapon::MAG7}),
		PaintKit(738, "-", "Orange Murano", {Weapon::Tec9}),
		PaintKit(739, "-", "Violet Murano", {Weapon::G3SG1}),
		PaintKit(740, "-", "Navy Murano", {Weapon::AUG}),
		PaintKit(741, "-", "Dark Filigree", {Weapon::P250}),
		PaintKit(742, "-", "Red Filigree", {Weapon::MAC10}),
		PaintKit(743, "-", "Orange Filigree", {Weapon::SSG08}),
		PaintKit(744, "-", "Baroque Red", {Weapon::P90}),
		PaintKit(745, "-", "Baroque Purple", {Weapon::AK47}),
		PaintKit(746, "-", "Baroque Orange", {Weapon::Nova}),
		PaintKit(747, "-", "Twin Turbo", {Weapon::DualBerettas}),
		PaintKit(748, "-", "Calf Skin", {Weapon::MAC10}),
		PaintKit(749, "-", "Vino Primo", {Weapon::P250}),
		PaintKit(750, "-", "Integrale", {Weapon::SG553}),
		PaintKit(751, "-", "Hand Brake", {Weapon::SSG08}),
		PaintKit(752, "-", "Fade", {Weapon::MP7}),
		PaintKit(753, "-", "Dirt Drop", {Weapon::MP5}),
		PaintKit(754, "-", "Rust Coat", {Weapon::MAG7}),
		PaintKit(755, "-", "Slide", {Weapon::MP9}),
		PaintKit(756, "-", "Gungnir", {Weapon::AWP}),
		PaintKit(757, "-", "Emerald Jörmungandr", {Weapon::DesertEagle}),
		PaintKit(758, "-", "Flame Jörmungandr", {Weapon::AUG}),
		PaintKit(759, "-", "Astral Jörmungandr", {Weapon::P90}),
		PaintKit(760, "-", "Frost Borre", {Weapon::XM1014}),
		PaintKit(761, "-", "Copper Borre", {Weapon::MAC10}),
		PaintKit(762, "-", "Red Stone", {Weapon::SSG08}),
		PaintKit(763, "-", "Mjölnir", {Weapon::Negev}),
		PaintKit(775, "-", "Facility Sketch", {Weapon::PPBizon}),
		PaintKit(776, "-", "Facility Negative", {Weapon::P90}),
		PaintKit(777, "-", "Facility Draft", {Weapon::P250}),
		PaintKit(778, "-", "Facility Dark", {Weapon::UMP45}),
		PaintKit(779, "-", "Random Access", {Weapon::AUG}),
		PaintKit(780, "-", "Mainframe", {Weapon::M4A4}),
		PaintKit(781, "-", "Co-Processor", {Weapon::MP5}),
		PaintKit(782, "-", "Motherboard", {Weapon::MP7}),
		PaintKit(783, "-", "Bulkhead", {Weapon::Negev}),
		PaintKit(784, "-", "Coolant", {Weapon::FiveSeven}),
		PaintKit(785, "-", "Mandrel", {Weapon::Nova}),
		PaintKit(786, "-", "Exchanger", {Weapon::P250}),
		PaintKit(787, "-", "Core Breach", {Weapon::MAG7}),
		PaintKit(788, "-", "Acheron", {Weapon::AWP}),
		PaintKit(789, "-", "Nuclear Garden", {Weapon::Glock18}),
		PaintKit(790, "-", "Cold Fusion", {Weapon::Galil}),
		PaintKit(791, "-", "Remote Control", {Weapon::Tec9}),
		PaintKit(792, "-", "Control Panel", {Weapon::M4A1S}),
		PaintKit(793, "-", "Converter", {Weapon::M4A4}),
		PaintKit(794, "-", "Sweeper", {Weapon::AUG}),
		PaintKit(795, "-", "Safety Net", {Weapon::AK47}),
		PaintKit(796, "-", "Check Engine", {Weapon::USPS}),
		PaintKit(797, "-", "Brake Light", {Weapon::SawedOff}),
		PaintKit(798, "-", "Nitro", {Weapon::R8Revolver, Weapon::MP5}),
		PaintKit(799, "-", "High Beam", {Weapon::Glock18}),
		PaintKit(800, "-", "Lab Rats", {Weapon::MP5}),
		PaintKit(801, "-", "Asiimov", {Weapon::AK47}),
		PaintKit(802, "-", "Momentum", {Weapon::UMP45}),
		PaintKit(803, "-", "Neo-Noir", {Weapon::AWP}),
		PaintKit(804, "-", "Modest Threat", {Weapon::MP9}),
		PaintKit(805, "-", "Mecha Industries", {Weapon::DesertEagle}),
		PaintKit(806, "-", "Scavenger", {Weapon::G3SG1}),
		PaintKit(807, "-", "Signal", {Weapon::Galil}),
		PaintKit(808, "-", "Oxide Blaze", {Weapon::Glock18}),
		PaintKit(809, "-", "Wood Fired", {Weapon::Nova}),
		PaintKit(810, "-", "Phosphor", {Weapon::MP5}),
		PaintKit(811, "-", "Magnesium", {Weapon::M4A4}),
		PaintKit(812, "-", "Pipe Down", {Weapon::MAC10}),
		PaintKit(813, "-", "Nevermore", {Weapon::P250}),
		PaintKit(814, "-", "Black Sand", {Weapon::SawedOff}),
		PaintKit(815, "-", "Danger Close", {Weapon::SG553}),
		PaintKit(816, "-", "Fubar", {Weapon::Tec9}),
		PaintKit(817, "-", "Flashback", {Weapon::USPS}),
		PaintKit(835, "-", "Crypsis", {Weapon::FAMAS}),
		PaintKit(836, "-", "Uncharted", {Weapon::AK47}),
		PaintKit(837, "-", "Angry Mob", {Weapon::FiveSeven}),
		PaintKit(838, "-", "Atheris", {Weapon::AWP}),
		PaintKit(839, "-", "Bamboozle", {Weapon::Tec9}),
		PaintKit(840, "-", "Whitefish", {Weapon::MAC10}),
		PaintKit(841, "-", "Light Rail", {Weapon::DesertEagle}),
		PaintKit(842, "-", "Akoben", {Weapon::Galil}),
		PaintKit(843, "-", "Skull Crusher", {Weapon::R8Revolver}),
		PaintKit(844, "-", "The Emperor", {Weapon::M4A4}),
		PaintKit(845, "-", "Momentum", {Weapon::AUG}),
		PaintKit(846, "-", "Gauss", {Weapon::MP5}),
		PaintKit(847, "-", "Mischief", {Weapon::MP7}),
		PaintKit(848, "-", "Verdigris", {Weapon::P250}),
		PaintKit(849, "-", "Off World", {Weapon::P90}),
		PaintKit(850, "-", "Incinegator", {Weapon::XM1014}),
		PaintKit(851, "-", "Moonrise", {Weapon::UMP45}),
		PaintKit(859, "-", "Emerald Quartz", {Weapon::CZ75}),
		PaintKit(860, "-", "Pyre", {Weapon::DualBerettas}),
		PaintKit(861, "-", "Barricade", {Weapon::SG553}),
		PaintKit(862, "-", "Moss Quartz", {Weapon::M4A1S}),
		PaintKit(863, "-", "Night Borre", {Weapon::FAMAS}),
		PaintKit(864, "-", "Candy Apple", {Weapon::SG553}),
		PaintKit(865, "-", "Stone Mosaico", {Weapon::SCAR20}),
		PaintKit(866, "-", "Canal Spray", {Weapon::R8Revolver}),
		PaintKit(867, "-", "Stained Glass", {Weapon::MP9}),
		PaintKit(868, "-", "Sea Calico", {Weapon::SSG08}),
		PaintKit(869, "-", "Sundown", {Weapon::FAMAS}),
		PaintKit(870, "-", "Jungle Thicket", {Weapon::SawedOff}),
		PaintKit(871, "-", "Surfwood", {Weapon::MAC10}),
		PaintKit(872, "-", "Bamboo Garden", {Weapon::MP5}),
		PaintKit(873, "-", "Seabird", {Weapon::PPBizon}),
		PaintKit(884, "-", "Embargo", {Weapon::PPBizon}),
		PaintKit(885, "-", "Rat Rod", {Weapon::AK47}),
		PaintKit(886, "-", "Arctic Wolf", {Weapon::AUG}),
		PaintKit(887, "-", "Containment Breach", {Weapon::AWP}),
		PaintKit(888, "-", "Acid Wash", {Weapon::MP5}),
		PaintKit(889, "-", "Decimator", {Weapon::Tec9}),
		PaintKit(890, "-", "Plume", {Weapon::Nova}),
		PaintKit(891, "-", "Black Sand", {Weapon::G3SG1}),
		PaintKit(892, "-", "Memento", {Weapon::R8Revolver}),
		PaintKit(893, "-", "Neon Ply", {Weapon::MP7}),
		PaintKit(894, "-", "Obsidian", {Weapon::P2000}),
		PaintKit(895, "-", "Balance", {Weapon::DualBerettas}),
		PaintKit(896, "-", "Torn", {Weapon::SCAR20}),
		PaintKit(897, "-", "Colony IV", {Weapon::SG553}),
		PaintKit(898, "-", "Stalker", {Weapon::MAC10}),
		PaintKit(899, "-", "Bloodshot", {Weapon::SSG08}),
		PaintKit(900, "-", "Warbird", {Weapon::M249}),
		PaintKit(902, "-", "Aztec", {Weapon::M249}),
		PaintKit(903, "-", "Elite 1.6", {Weapon::DualBerettas}),
		PaintKit(904, "-", "Decommissioned", {Weapon::FAMAS}),
		PaintKit(905, "-", "Flash Out", {Weapon::Tec9}),
		PaintKit(906, "-", "Buddy", {Weapon::FiveSeven}),
		PaintKit(907, "-", "Inferno", {Weapon::P250}),
		PaintKit(908, "-", "Classic Crate", {Weapon::MAC10}),
		PaintKit(909, "-", "Popdog", {Weapon::MAG7}),
		PaintKit(910, "-", "Hydra", {Weapon::MP9}),
		PaintKit(911, "-", "Nostalgia", {Weapon::P90}),
		PaintKit(913, "-", "Death by Puppy", {Weapon::AUG}),
		PaintKit(914, "-", "Assault", {Weapon::SCAR20}),
		PaintKit(915, "-", "Agent", {Weapon::MP5}),
		PaintKit(916, "-", "Plastique", {Weapon::UMP45}),
		PaintKit(917, "-", "Wildfire", {Weapon::AWP}),
		PaintKit(918, "-", "Sacrifice", {Weapon::Glock18}),
		PaintKit(919, "-", "Commemoration", {Weapon::FAMAS}),
		PaintKit(920, "-", "Boroque Sand", {Weapon::Negev}),
		PaintKit(941, "-", "Phantom Disruptor", {Weapon::AK47}),
		PaintKit(942, "-", "Tom Cat", {Weapon::AUG}),
		PaintKit(943, "-", "Capillary", {Weapon::AWP}),
		PaintKit(944, "-", "Distressed", {Weapon::CZ75}),
		PaintKit(945, "-", "Blue Ply", {Weapon::DesertEagle}),
		PaintKit(946, "-", "Player Two", {Weapon::M4A1S}),
		PaintKit(947, "-", "Disco Tech", {Weapon::MAC10}),
		PaintKit(948, "-", "Justice", {Weapon::MAG7}),
		PaintKit(949, "-", "Desert Strike", {Weapon::MP5}),
		PaintKit(950, "-", "Prototype", {Weapon::Negev}),
		PaintKit(951, "-", "Acid Etched", {Weapon::P2000}),
		PaintKit(952, "-", "Bone Forged", {Weapon::R8Revolver}),
		PaintKit(953, "-", "Apocalypto", {Weapon::SawedOff}),
		PaintKit(954, "-", "Enforcer", {Weapon::SCAR20}),
		PaintKit(955, "-", "Darkwing", {Weapon::SG553}),
		PaintKit(956, "-", "Fever Dream", {Weapon::SSG08}),
		PaintKit(957, "-", "Bullet Queen", {Weapon::Glock18}),
		PaintKit(958, "-", "Ultralight", {Weapon::Negev}),
		PaintKit(959, "-", "Legion of Anubis", {Weapon::AK47}),
		PaintKit(960, "-", "Gnarled", {Weapon::P2000}),
		PaintKit(961, "-", "Monster Call", {Weapon::MAG7}),
		PaintKit(962, "-", "Printstream", {Weapon::DesertEagle}),
		PaintKit(963, "-", "Vogue", {Weapon::Glock18}),
		PaintKit(964, "-", "Brother", {Weapon::Tec9}),
		PaintKit(965, "-", "Allure", {Weapon::MAC10}),
		PaintKit(966, "-", "Ol' Rusty", {Weapon::SG553}),
		PaintKit(967, "-", "Mainframe 001", {Weapon::SSG08}),
		PaintKit(968, "-", "Cassette", {Weapon::P250}),
		PaintKit(969, "-", "Freight", {Weapon::P90}),
		PaintKit(970, "-", "Entombed", {Weapon::XM1014}),
		PaintKit(971, "-", "Tooth Fairy", {Weapon::M4A4}),
		PaintKit(972, "-", "Connexion", {Weapon::Galil}),
		PaintKit(973, "-", "Runic", {Weapon::PPBizon}),
		PaintKit(974, "-", "Kitbash", {Weapon::MP5}),
		PaintKit(975, "-", "Exoskeleton", {Weapon::AWP}),
		PaintKit(976, "-", "Vendetta", {Weapon::CZ75}),
		PaintKit(977, "-", "Cocoa Rampage", {Weapon::P90}),
		PaintKit(978, "-", "Dezastre", {Weapon::DualBerettas}),
		PaintKit(979, "-", "Fairy Tale", {Weapon::FiveSeven}),
		PaintKit(980, "-", "Digital Mesh", {Weapon::G3SG1}),
		PaintKit(981, "-", "Vandal", {Weapon::Galil}),
		PaintKit(982, "-", "Contaminant", {Weapon::P250}),
		PaintKit(983, "-", "Deep Relief", {Weapon::M249}),
		PaintKit(984, "-", "Printstream", {Weapon::M4A1S}),
		PaintKit(985, "-", "Cyber Security", {Weapon::M4A4}),
		PaintKit(986, "-", "Condition Zero", {Weapon::MP5}),
		PaintKit(987, "-", "Clear Polymer", {Weapon::Nova}),
		PaintKit(988, "-", "Neo-Noir", {Weapon::Glock18}),
		PaintKit(989, "-", "Parallax", {Weapon::SSG08}),
		PaintKit(990, "-", "Gold Bismuth", {Weapon::UMP45}),
		PaintKit(991, "-", "Monster Mashup", {Weapon::USPS}),
		PaintKit(992, "-", "The Bronze", {Weapon::DesertEagle}),
		PaintKit(993, "-", "Global Offensive", {Weapon::M4A4}),
		PaintKit(994, "-", "Charter", {Weapon::XM1014}),
		PaintKit(995, "-", "Surveillance", {Weapon::AUG}),
		PaintKit(996, "-", "Threat Detected", {Weapon::SSG08}),
		PaintKit(997, "-", "Dispatch", {Weapon::P2000}),
		PaintKit(998, "-", "Switch Board", {Weapon::DualBerettas}),
		PaintKit(999, "-", "Prime Conspiracy", {Weapon::FAMAS}),
		PaintKit(1000, "-", "Run and Hide", {Weapon::P90}),
		PaintKit(1001, "-", "Welcome to the Jungle", {Weapon::M4A1S}),
		PaintKit(1002, "-", "Berries And Cherries", {Weapon::FiveSeven}),
		PaintKit(1003, "-", "Crime Scene", {Weapon::UMP45}),
		PaintKit(1004, "-", "X-Ray", {Weapon::AK47}),
		PaintKit(1005, "-", "Heist", {Weapon::DualBerettas}),
		PaintKit(1006, "-", "Night Heist", {Weapon::DesertEagle}),
		PaintKit(1007, "-", "Vault Heist", {Weapon::MP7}),
		PaintKit(1008, "-", "Houndstooth", {Weapon::UMP45}),
		PaintKit(1009, "-", "Hot Snakes", {Weapon::MAC10}),
		PaintKit(1010, "-", "Phoenix Chalk", {Weapon::Tec9}),
		PaintKit(1011, "-", "Phoenix Marker", {Weapon::R8Revolver}),
		PaintKit(1012, "-", "Phoenix Stencil", {Weapon::Negev}),
		PaintKit(1013, "-", "Phoenix Blacklight", {Weapon::Galil}),
		PaintKit(1014, "-", "Clay Ambush", {Weapon::SawedOff}),
		PaintKit(1015, "-", "Tiger Pit", {Weapon::P90}),
		PaintKit(1016, "-", "Franklin", {Weapon::Glock18}),
		PaintKit(1017, "-", "Blue Phosphor", {Weapon::M4A1S}),
		PaintKit(1018, "-", "Panthera onca", {Weapon::AK47}),
		PaintKit(1019, "-", "Panther Camo", {Weapon::P2000}),
		PaintKit(1020, "-", "Ancient Earth", {Weapon::P90}),
		PaintKit(1021, "-", "Ancient Lore", {Weapon::XM1014}),
		PaintKit(1022, "-", "Lush Ruins", {Weapon::SG553}),
		PaintKit(1023, "-", "Tall Grass", {Weapon::MP7}),
		PaintKit(1024, "-", "Blast From the Past", {Weapon::Tec9}),
		PaintKit(1025, "-", "Gold Brick", {Weapon::MAC10}),
		PaintKit(1026, "-", "Fade", {Weapon::AWP}),
		PaintKit(1027, "-", "Target Acquired", {Weapon::USPS}),
		PaintKit(1028, "-", "Magna Carta", {Weapon::SCAR20}),
		PaintKit(1029, "-", "Silk Tiger", {Weapon::AWP}),
		PaintKit(1030, "-", "Bengal Tiger", {Weapon::P250}),
		PaintKit(1031, "-", "Ancient Visions", {Weapon::USPS}),
		PaintKit(1032, "-", "Dusk Ruins", {Weapon::Galil}),
		PaintKit(1033, "-", "Carved Jade", {Weapon::AUG}),
		PaintKit(1034, "-", "Ancient Ritual", {Weapon::G3SG1}),
	};
};

/*
std::vector<std::vector<std::string>> Skins::WeaponGroups = {
	{"Pistol", "pistol",
		"Glock-18", "glock",
		"P2000", "hkp2000",
		"USP-S", "usp_silencer",
		"Dual Berettas", "elite", // lol wtf valve
		"P250", "p250",
		"Tec-9", "tec9",
		"Five-Seven", "fn57",
		"CZ-75", "cz75a",
		"Desert Eagle",	"deagle",
		"R8 Revolver", "revolver"
	},
	{"Heavy", "heavy",
		"Nova", "nove",
		"XM1014", "xm1014",
		"Sawed-Off", "sawedoff", // TODO check if this is right
		"MAG-7", "mag7",
		"M249", "m249",
		"Negev", "negev",
	},
	{"SMG", "smg",
		"MP9", "mp9", 
		"MAC-10", "mac10", 
		"MP7", "mp7", 
		"MP5", "mp5sd", 
		"UMP-45", "ump45", 
		"P90", "p90", 
		"PP-Bizon", "bizon"
	},
	{"Rifle", "rifle",
		"FAMAS", "famas",
		"Galil", "galilar",
		"M4A4", "m4a4",
		"AK-47", "ak47",
		"M4A1-S", "m4a1_silencer",
		"SSG 08", "ssg08",
		"AUG", "aug",
		"SG 553", "sg556", // valve why, wtf?
		"AWP", "awp",
		"SCAR-20", "scar20",
		"G3SG1", "g3sg1"
	},
	{"Other", "other",
		"Zeus x27", "taser",
		"C4", "c4",
		"Incendiary", "incgrenade",
		"Molotov", "molotov", 
		"Decoy", "decoy",
		"Flashbang", "flashbang",
		"HE Grenade", "hegrenade", 
		"Smoke", "smokegrenade"
	},
};
*/