#include "SkinConstants.hpp"


namespace Skins
{

	std::vector<std::string> WeaponNames = {
		"Glock-18",
		"P2000",
		"USP-S",
		"Dual Berettas",
		"P250",
		"Tec-9",
		"Five-Seven",
		"CZ-75",
		"Desert Eagle",
		"R8 Revolver",
		"Nova",
		"XM1014",
		"Sawed-Off",
		"MAG-7",
		"M249",
		"Negev",
		"MP9",
		"MAC-10",
		"MP7",
		"MP5",
		"UMP-45",
		"P90",
		"PP-Bizon",
		"FAMAS",
		"Galil",
		"M4A4",
		"AK-47",
		"M4A1-S",
		"SSG 08",
		"AUG",
		"SG 553",
		"AWP",
		"SCAR-20",
		"G3SG1",
		"Zeus x27",
		"C4",
		"Incendiary",
		"Molotov",
		"Decoy",
		"Flashbang",
		"HE Grenade",
		"Smoke"
	};

	std::vector<std::string> WeaponGroupNames = {
		"Pistol",
		"Heavy",
		"SMG",
		"Rifle",
		"Other",
	};

	std::vector<std::vector<Weapon>> WeaponGroupWeapons = {
		// Pistol
		{
			Weapon::Glock18,
			Weapon::P2000,
			Weapon::USPS,
			Weapon::DualBerettas,
			Weapon::P250,
			Weapon::Tec9,
			Weapon::FiveSeven,
			Weapon::CZ75,
			Weapon::DesertEagle,
			Weapon::R8Revolver,
		},
		// Heavy
		{
			Weapon::Nova,
			Weapon::XM1014,
			Weapon::SawedOff,
			Weapon::MAG7,
			Weapon::M249,
			Weapon::Negev,
		},
		// SMG
		{
			Weapon::MP9,
			Weapon::MAC10,
			Weapon::MP7,
			Weapon::MP5,
			Weapon::UMP45,
			Weapon::P90,
			Weapon::PPBizon,
		},
		// Rifle
		{
			Weapon::FAMAS,
			Weapon::Galil,
			Weapon::M4A4,
			Weapon::AK47,
			Weapon::M4A1S,
			Weapon::SSG08,
			Weapon::AUG,
			Weapon::SG553,
			Weapon::AWP,
			Weapon::SCAR20,
			Weapon::G3SG1,
		},
		// Other
		{
			Weapon::C4,
			Weapon::Incendiary,
			Weapon::Molotov,
			Weapon::Decoy,
			Weapon::Flashbang,
			Weapon::HE,
			Weapon::Smoke,
		},
	};

	std::vector<std::string> KnifeNames = {
		"Nomad",
		"Skeleton",
		"Survival",
		"Paracord",
		"Classic",
		"Bowie",
		"Butterfly",
		"Falchion",
		"Flip",
		"Gut",
        "Huntsman",
		"Karambit",
        "Bayonet",
		"M9 Bayonet",
		"Navaja",
		"Shadow Daggers",
		"Stiletto",
		"Talon",
		"Ursus",
		"T Default",
		"CT Default"
	};

	std::vector<std::string> GloveNames = {

	};

#define ENUM2BIT(v) ((uint64_t)1 << (uint64_t)(v))
	std::vector<PaintKit> PaintKits
	{
		PaintKit(0, "None"),
        PaintKit(2, XOR("Groundwater"), ENUM2BIT(Weapon::Glock18) | ENUM2BIT(Weapon::Tec9)),
        PaintKit(3, XOR("Candy Apple"), ENUM2BIT(Weapon::Glock18) | ENUM2BIT(Weapon::FiveSeven) | ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::MAC10) | ENUM2BIT(Weapon::PPBizon)),
        PaintKit(5, XOR("Forest DDPAT"), ENUM2BIT(Weapon::SawedOff) | ENUM2BIT(Weapon::MP7)),
        PaintKit(6, XOR("Arctic Camo"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(8, XOR("Desert Storm"), ENUM2BIT(Weapon::M4A4) | ENUM2BIT(Weapon::G3SG1)),
        PaintKit(9, XOR("Bengal Tiger"), ENUM2BIT(Weapon::AUG)),
        PaintKit(10, XOR("Copperhead"), ENUM2BIT(Weapon::AUG)),
        PaintKit(11, XOR("Skulls"), ENUM2BIT(Weapon::MP7)),
        PaintKit(12, XOR("Crimson Web"), ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(13, XOR("Blue Streak"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(14, XOR("Red Laminate"), ENUM2BIT(Weapon::AK47)),
        PaintKit(15, XOR("Gunsmoke"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::MP7) | ENUM2BIT(Weapon::UMP45)),
        PaintKit(16, XOR("Jungle Tiger"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(17, XOR("Urban DDPAT"), ENUM2BIT(Weapon::Tec9) | ENUM2BIT(Weapon::DesertEagle) | ENUM2BIT(Weapon::MAC10) | ENUM2BIT(Weapon::UMP45) | ENUM2BIT(Weapon::M4A4)),
        PaintKit(20, XOR("Virus"), ENUM2BIT(Weapon::P90)),
        PaintKit(21, XOR("Granite Marbleized"), ENUM2BIT(Weapon::P2000)),
        PaintKit(22, XOR("Contrast Spray"), ENUM2BIT(Weapon::M249) | ENUM2BIT(Weapon::FAMAS)),
        PaintKit(25, XOR("Forest Leaves"), ENUM2BIT(Weapon::USPS) | ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::PPBizon)),
        PaintKit(26, XOR("Lichen Dashed"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(27, XOR("Bone Mask"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(28, XOR("Anodized Navy"), ENUM2BIT(Weapon::DualBerettas) | ENUM2BIT(Weapon::Negev) | ENUM2BIT(Weapon::MP7) | ENUM2BIT(Weapon::SG553)),
        PaintKit(30, XOR("Snake Camo"), ENUM2BIT(Weapon::SawedOff) | ENUM2BIT(Weapon::AWP)),
        PaintKit(32, XOR("Silver"), ENUM2BIT(Weapon::P2000) | ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::MAG7) | ENUM2BIT(Weapon::MAC10)),
        PaintKit(33, XOR("Hot Rod"), ENUM2BIT(Weapon::MP9) | ENUM2BIT(Weapon::AUG)),
        PaintKit(34, XOR("Metallic DDPAT"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::MAG7)),
        PaintKit(36, XOR("Ossified"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(37, XOR("Blaze"), ENUM2BIT(Weapon::DesertEagle) | ENUM2BIT(Weapon::UMP45)),
        PaintKit(38, XOR("Fade"), ENUM2BIT(Weapon::Glock18) | ENUM2BIT(Weapon::MAC10)),
        PaintKit(39, XOR("Bulldozer"), ENUM2BIT(Weapon::MAG7) | ENUM2BIT(Weapon::MP9) | ENUM2BIT(Weapon::SG553)),
        PaintKit(40, XOR("Night"), ENUM2BIT(Weapon::Glock18) | ENUM2BIT(Weapon::DesertEagle) | ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(41, XOR("Copper"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(42, XOR("Blue Steel"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(43, XOR("Stained"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(44, XOR("Case Hardened"), ENUM2BIT(Weapon::FiveSeven) | ENUM2BIT(Weapon::AK47)),
        PaintKit(46, XOR("Contractor"), ENUM2BIT(Weapon::DualBerettas) | ENUM2BIT(Weapon::FiveSeven) | ENUM2BIT(Weapon::AUG) | ENUM2BIT(Weapon::SCAR20) | ENUM2BIT(Weapon::G3SG1)),
        PaintKit(47, XOR("Colony"), ENUM2BIT(Weapon::DualBerettas) | ENUM2BIT(Weapon::FAMAS) | ENUM2BIT(Weapon::AUG)),
        PaintKit(48, XOR("Dragon Tattoo"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(51, XOR("Lightning Strike"), ENUM2BIT(Weapon::AWP)),
        PaintKit(60, XOR("Dark Water"), ENUM2BIT(Weapon::USPS) | ENUM2BIT(Weapon::FAMAS) | ENUM2BIT(Weapon::M4A1S) | ENUM2BIT(Weapon::SSG08)),
        PaintKit(61, XOR("Hypnotic"), ENUM2BIT(Weapon::DesertEagle) | ENUM2BIT(Weapon::MP9) | ENUM2BIT(Weapon::SG553)),
        PaintKit(62, XOR("Bloomstick"), ENUM2BIT(Weapon::Nova)),
        PaintKit(67, XOR("Cold Blooded"), ENUM2BIT(Weapon::P90)),
        PaintKit(70, XOR("Carbon Fiber"), ENUM2BIT(Weapon::MAG7) | ENUM2BIT(Weapon::UMP45) | ENUM2BIT(Weapon::PPBizon) | ENUM2BIT(Weapon::SCAR20)),
        PaintKit(71, XOR("Scorpion"), ENUM2BIT(Weapon::P2000)),
        PaintKit(72, XOR("Safari Mesh"), ENUM2BIT(Weapon::AK47) | ENUM2BIT(Weapon::AWP) | ENUM2BIT(Weapon::G3SG1)),
        PaintKit(73, XOR("Wings"), ENUM2BIT(Weapon::AUG)),
        PaintKit(74, XOR("Polar Camo"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(75, XOR("Blizzard Marbleized"), ENUM2BIT(Weapon::M249)),
        PaintKit(76, XOR("Winter Forest"), ENUM2BIT(Weapon::Galil)),
        PaintKit(77, XOR("Boreal Forest"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::M4A1S)),
        PaintKit(78, XOR("Forest Night"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(83, XOR("Orange DDPAT"), ENUM2BIT(Weapon::SawedOff) | ENUM2BIT(Weapon::Galil)),
        PaintKit(84, XOR("Pink DDPAT"), ENUM2BIT(Weapon::AWP)),
        PaintKit(90, XOR("Mudder"), ENUM2BIT(Weapon::DesertEagle) | ENUM2BIT(Weapon::UMP45)),
        PaintKit(92, XOR("Cyanospatter"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(93, XOR("Caramel"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(95, XOR("Grassland"), ENUM2BIT(Weapon::P2000) | ENUM2BIT(Weapon::XM1014)),
        PaintKit(96, XOR("Blue Spruce"), ENUM2BIT(Weapon::XM1014) | ENUM2BIT(Weapon::SSG08)),
        PaintKit(98, XOR("Ultraviolet"), ENUM2BIT(Weapon::MAC10) | ENUM2BIT(Weapon::SG553)),
        PaintKit(99, XOR("Sand Dune"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::MAG7) | ENUM2BIT(Weapon::SSG08)),
        PaintKit(100, XOR("Storm"), ENUM2BIT(Weapon::MAG7) | ENUM2BIT(Weapon::MP9) | ENUM2BIT(Weapon::P90) | ENUM2BIT(Weapon::AUG) | ENUM2BIT(Weapon::SCAR20)),
        PaintKit(101, XOR("Tornado"), ENUM2BIT(Weapon::MAC10) | ENUM2BIT(Weapon::Galil) | ENUM2BIT(Weapon::M4A4) | ENUM2BIT(Weapon::SG553)),
        PaintKit(102, XOR("Whiteout"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::MP7)),
        PaintKit(104, XOR("Grassland Leaves"), ENUM2BIT(Weapon::P2000)),
        PaintKit(107, XOR("Polar Mesh"), ENUM2BIT(Weapon::Nova)),
        PaintKit(110, XOR("Condemned"), ENUM2BIT(Weapon::AUG)),
        PaintKit(111, XOR("Glacier Mesh"), ENUM2BIT(Weapon::P90)),
        PaintKit(116, XOR("Sand Mesh"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(119, XOR("Sage Spray"), ENUM2BIT(Weapon::SawedOff) | ENUM2BIT(Weapon::Galil)),
        PaintKit(122, XOR("Jungle Spray"), ENUM2BIT(Weapon::AK47)),
        PaintKit(124, XOR("Sand Spray"), ENUM2BIT(Weapon::P90)),
        PaintKit(125, XOR("X-Ray"), ENUM2BIT(Weapon::P250)),
        PaintKit(135, XOR("Urban Perforated"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(136, XOR("Waves Perforated"), ENUM2BIT(Weapon::SG553)),
        PaintKit(141, XOR("Orange Peel"), ENUM2BIT(Weapon::FiveSeven) | ENUM2BIT(Weapon::MP9) | ENUM2BIT(Weapon::MP7)),
        PaintKit(147, XOR("Jungle Dashed"), ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::SSG08) | ENUM2BIT(Weapon::G3SG1)),
        PaintKit(148, XOR("Sand Dashed"), ENUM2BIT(Weapon::MP9) | ENUM2BIT(Weapon::PPBizon)),
        PaintKit(149, XOR("Urban Dashed"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(151, XOR("Jungle"), ENUM2BIT(Weapon::FiveSeven) | ENUM2BIT(Weapon::M249)),
        PaintKit(153, XOR("Demolition"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(154, XOR("Afterimage"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(155, XOR("Bullet Rain"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(156, XOR("Death by Kitty"), ENUM2BIT(Weapon::P90)),
        PaintKit(157, XOR("Palm"), ENUM2BIT(Weapon::MAC10) | ENUM2BIT(Weapon::SCAR20)),
        PaintKit(158, XOR("Walnut"), ENUM2BIT(Weapon::Nova)),
        PaintKit(159, XOR("Brass"), ENUM2BIT(Weapon::Glock18) | ENUM2BIT(Weapon::Tec9) | ENUM2BIT(Weapon::PPBizon) | ENUM2BIT(Weapon::SCAR20)),
        PaintKit(162, XOR("Splash"), ENUM2BIT(Weapon::P250)),
        PaintKit(164, XOR("Modern Hunter"), ENUM2BIT(Weapon::P250) | ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::PPBizon) | ENUM2BIT(Weapon::M4A4)),
        PaintKit(165, XOR("Splash Jam"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(166, XOR("Blaze Orange"), ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::XM1014)),
        PaintKit(167, XOR("Radiation Hazard"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(168, XOR("Nuclear Threat"), ENUM2BIT(Weapon::P250)),
        PaintKit(169, XOR("Fallout Warning"), ENUM2BIT(Weapon::XM1014) | ENUM2BIT(Weapon::UMP45) | ENUM2BIT(Weapon::P90)),
        PaintKit(170, XOR("Predator"), ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::M249) | ENUM2BIT(Weapon::AK47)),
        PaintKit(171, XOR("Irradiated Alert"), ENUM2BIT(Weapon::SawedOff) | ENUM2BIT(Weapon::MAG7) | ENUM2BIT(Weapon::PPBizon)),
        PaintKit(172, XOR("Black Laminate"), ENUM2BIT(Weapon::AK47)),
        PaintKit(174, XOR("BOOM"), ENUM2BIT(Weapon::AWP)),
        PaintKit(175, XOR("Scorched"), ENUM2BIT(Weapon::MP7) | ENUM2BIT(Weapon::UMP45) | ENUM2BIT(Weapon::P90)),
        PaintKit(176, XOR("Faded Zebra"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(177, XOR("Memento"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(178, XOR("Doomkitty"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(179, XOR("Nuclear Threat"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(180, XOR("Fire Serpent"), ENUM2BIT(Weapon::AK47)),
        PaintKit(181, XOR("Corticera"), ENUM2BIT(Weapon::AWP)),
        PaintKit(182, XOR("Emerald Dragon"), ENUM2BIT(Weapon::P90)),
        PaintKit(183, XOR("Overgrowth"), ENUM2BIT(Weapon::USPS)),
        PaintKit(184, XOR("Corticera"), ENUM2BIT(Weapon::P2000)),
        PaintKit(185, XOR("Golden Koi"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(186, XOR("Wave Spray"), ENUM2BIT(Weapon::SG553)),
        PaintKit(187, XOR("Zirka"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(188, XOR("Graven"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(189, XOR("Bright Water"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(190, XOR("Black Limba"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(191, XOR("Tempest"), ENUM2BIT(Weapon::Nova)),
        PaintKit(192, XOR("Shattered"), ENUM2BIT(Weapon::Galil)),
        PaintKit(193, XOR("Bone Pile"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(194, XOR("Spitfire"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(195, XOR("Demeter"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(196, XOR("Emerald"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(197, XOR("Anodized Navy"), ENUM2BIT(Weapon::AUG)),
        PaintKit(198, XOR("Hazard"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(199, XOR("Dry Season"), ENUM2BIT(Weapon::MP9)),
        PaintKit(200, XOR("Mayan Dreams"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(201, XOR("Palm"), ENUM2BIT(Weapon::Negev)),
        PaintKit(202, XOR("Jungle DDPAT"), ENUM2BIT(Weapon::M249)),
        PaintKit(203, XOR("Rust Coat"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(204, XOR("Mosaico"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(205, XOR("Jungle"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(206, XOR("Tornado"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(207, XOR("Facets"), ENUM2BIT(Weapon::P250)),
        PaintKit(208, XOR("Sand Dune"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(209, XOR("Groundwater"), ENUM2BIT(Weapon::MP7)),
        PaintKit(210, XOR("Anodized Gunmetal"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(211, XOR("Ocean Foam"), ENUM2BIT(Weapon::P2000)),
        PaintKit(212, XOR("Graphite"), ENUM2BIT(Weapon::AWP)),
        PaintKit(213, XOR("Ocean Foam"), ENUM2BIT(Weapon::MP7)),
        PaintKit(214, XOR("Graphite"), ENUM2BIT(Weapon::Nova)),
        PaintKit(215, XOR("X-Ray"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(216, XOR("Blue Titanium"), ENUM2BIT(Weapon::Tec9) | ENUM2BIT(Weapon::Galil)),
        PaintKit(217, XOR("Blood Tiger"), ENUM2BIT(Weapon::USPS) | ENUM2BIT(Weapon::M4A1S)),
        PaintKit(218, XOR("Hexane"), ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::FAMAS)),
        PaintKit(219, XOR("Hive"), ENUM2BIT(Weapon::P250)),
        PaintKit(220, XOR("Hemoglobin"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(221, XOR("Serum"), ENUM2BIT(Weapon::USPS)),
        PaintKit(222, XOR("Blood in the Water"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(223, XOR("Nightshade"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(224, XOR("Water Sigil"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(225, XOR("Ghost Camo"), ENUM2BIT(Weapon::Nova)),
        PaintKit(226, XOR("Blue Laminate"), ENUM2BIT(Weapon::AK47)),
        PaintKit(227, XOR("Electric Hive"), ENUM2BIT(Weapon::AWP)),
        PaintKit(228, XOR("Blind Spot"), ENUM2BIT(Weapon::P90)),
        PaintKit(229, XOR("Azure Zebra"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(230, XOR("Steel Disruption"), ENUM2BIT(Weapon::Glock18) | ENUM2BIT(Weapon::P250)),
        PaintKit(231, XOR("Cobalt Disruption"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(232, XOR("Crimson Web"), ENUM2BIT(Weapon::DesertEagle) | ENUM2BIT(Weapon::SCAR20)),
        PaintKit(233, XOR("Tropical Storm"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(234, XOR("Ash Wood"), ENUM2BIT(Weapon::P90)),
        PaintKit(235, XOR("VariCamo"), ENUM2BIT(Weapon::Tec9) | ENUM2BIT(Weapon::Galil) | ENUM2BIT(Weapon::M4A1S) | ENUM2BIT(Weapon::G3SG1)),
        PaintKit(236, XOR("Night Ops"), ENUM2BIT(Weapon::USPS) | ENUM2BIT(Weapon::PPBizon)),
        PaintKit(237, XOR("Urban Rubble"), ENUM2BIT(Weapon::DesertEagle) | ENUM2BIT(Weapon::Galil)),
        PaintKit(238, XOR("VariCamo Blue"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(240, XOR("CaliCamo"), ENUM2BIT(Weapon::XM1014) | ENUM2BIT(Weapon::Negev)),
        PaintKit(241, XOR("Hunting Blind"), ENUM2BIT(Weapon::Galil)),
        PaintKit(242, XOR("Army Mesh"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(243, XOR("Gator Mesh"), ENUM2BIT(Weapon::M249) | ENUM2BIT(Weapon::SG553)),
        PaintKit(244, XOR("Teardown"), ENUM2BIT(Weapon::P90) | ENUM2BIT(Weapon::FAMAS)),
        PaintKit(245, XOR("Army Recon"), ENUM2BIT(Weapon::MP7)),
        PaintKit(246, XOR("Amber Fade"), ENUM2BIT(Weapon::P2000) | ENUM2BIT(Weapon::SawedOff) | ENUM2BIT(Weapon::MAC10)),
        PaintKit(247, XOR("Damascus Steel"), ENUM2BIT(Weapon::SG553)),
        PaintKit(248, XOR("Red Quartz"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(249, XOR("Cobalt Quartz"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(250, XOR("Full Stop"), ENUM2BIT(Weapon::SawedOff) | ENUM2BIT(Weapon::MP7)),
        PaintKit(251, XOR("Pit Viper"), ENUM2BIT(Weapon::AWP)),
        PaintKit(252, XOR("Silver Quartz"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(253, XOR("Acid Fade"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(254, XOR("Nitro"), ENUM2BIT(Weapon::FiveSeven) | ENUM2BIT(Weapon::M4A1S)),
        PaintKit(255, XOR("Asiimov"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(256, XOR("The Kraken"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(257, XOR("Guardian"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(258, XOR("Mehndi"), ENUM2BIT(Weapon::P250)),
        PaintKit(259, XOR("Redline"), ENUM2BIT(Weapon::AWP)),
        PaintKit(260, XOR("Pulse"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(261, XOR("Marina"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(262, XOR("Rose Iron"), ENUM2BIT(Weapon::MP9)),
        PaintKit(263, XOR("Rising Skull"), ENUM2BIT(Weapon::Nova)),
        PaintKit(264, XOR("Sandstorm"), ENUM2BIT(Weapon::Galil)),
        PaintKit(265, XOR("Kami"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(266, XOR("Magma"), ENUM2BIT(Weapon::M249)),
        PaintKit(267, XOR("Cobalt Halftone"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(268, XOR("Tread Plate"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(269, XOR("The Fuschia Is Now"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(270, XOR("Victoria"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(271, XOR("Undertow"), ENUM2BIT(Weapon::P250)),
        PaintKit(272, XOR("Titanium Bit"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(273, XOR("Heirloom"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(274, XOR("Copper Galaxy"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(275, XOR("Red FragCam"), ENUM2BIT(Weapon::P2000)),
        PaintKit(276, XOR("Panther"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(277, XOR("Stainless"), ENUM2BIT(Weapon::USPS)),
        PaintKit(278, XOR("Blue Fissure"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(279, XOR("Asiimov"), ENUM2BIT(Weapon::AWP)),
        PaintKit(280, XOR("Chameleon"), ENUM2BIT(Weapon::AUG)),
        PaintKit(281, XOR("Corporal"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(282, XOR("Redline"), ENUM2BIT(Weapon::AK47)),
        PaintKit(283, XOR("Trigon"), ENUM2BIT(Weapon::P90)),
        PaintKit(284, XOR("Heat"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(285, XOR("Terrain"), ENUM2BIT(Weapon::Negev)),
        PaintKit(286, XOR("Antique"), ENUM2BIT(Weapon::Nova)),
        PaintKit(287, XOR("Pulse"), ENUM2BIT(Weapon::SG553)),
        PaintKit(288, XOR("Sergeant"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(289, XOR("Sandstorm"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(290, XOR("Guardian"), ENUM2BIT(Weapon::USPS)),
        PaintKit(291, XOR("Heaven Guard"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(293, XOR("Death Rattle"), ENUM2BIT(Weapon::Glock18) | ENUM2BIT(Weapon::PPBizon)),
        PaintKit(294, XOR("Green Apple"), ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::G3SG1)),
        PaintKit(295, XOR("Franklin"), ENUM2BIT(Weapon::P250)),
        PaintKit(296, XOR("Meteorite"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(297, XOR("Tuxedo"), ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::Galil)),
        PaintKit(298, XOR("Army Sheen"), ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::Negev) | ENUM2BIT(Weapon::MP9) | ENUM2BIT(Weapon::SG553) | ENUM2BIT(Weapon::SCAR20)),
        PaintKit(299, XOR("Caged Steel"), ENUM2BIT(Weapon::Nova)),
        PaintKit(300, XOR("Emerald Pinstripe"), ENUM2BIT(Weapon::AK47)),
        PaintKit(301, XOR("Atomic Alloy"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(302, XOR("Vulcan"), ENUM2BIT(Weapon::AK47)),
        PaintKit(303, XOR("Isaac"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(304, XOR("Slashed"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(305, XOR("Torque"), ENUM2BIT(Weapon::AUG)),
        PaintKit(306, XOR("Antique"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(307, XOR("Retribution"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(308, XOR("Kami"), ENUM2BIT(Weapon::Galil)),
        PaintKit(309, XOR("Howl"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(310, XOR("Curse"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(311, XOR("Desert Warfare"), ENUM2BIT(Weapon::P90)),
        PaintKit(312, XOR("Cyrex"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(313, XOR("Orion"), ENUM2BIT(Weapon::USPS)),
        PaintKit(314, XOR("Heaven Guard"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(315, XOR("Poison Dart"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(316, XOR("Jaguar"), ENUM2BIT(Weapon::AK47)),
        PaintKit(317, XOR("Bratatat"), ENUM2BIT(Weapon::Negev)),
        PaintKit(318, XOR("Road Rash"), ENUM2BIT(Weapon::USPS)),
        PaintKit(319, XOR("Detour"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(320, XOR("Red Python"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(321, XOR("Master Piece"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(322, XOR("Nitro"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(323, XOR("Rust Coat"), ENUM2BIT(Weapon::Nova) | ENUM2BIT(Weapon::SawedOff)),
        PaintKit(325, XOR("Chalice"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(326, XOR("Knight"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(327, XOR("Chainmail"), ENUM2BIT(Weapon::P2000) | ENUM2BIT(Weapon::MAG7)),
        PaintKit(328, XOR("Hand Cannon"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(329, XOR("Dark Age"), ENUM2BIT(Weapon::MP9)),
        PaintKit(330, XOR("Briar"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(332, XOR("Royal Blue"), ENUM2BIT(Weapon::USPS)),
        PaintKit(333, XOR("Indigo"), ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::MAC10) | ENUM2BIT(Weapon::UMP45)),
        PaintKit(334, XOR("Twist"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(335, XOR("Module"), ENUM2BIT(Weapon::P90)),
        PaintKit(336, XOR("Desert-Strike"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(337, XOR("Tatter"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(338, XOR("Pulse"), ENUM2BIT(Weapon::P2000)),
        PaintKit(339, XOR("Caiman"), ENUM2BIT(Weapon::USPS)),
        PaintKit(340, XOR("Jet Set"), ENUM2BIT(Weapon::AK47)),
        PaintKit(341, XOR("First Class"), ENUM2BIT(Weapon::AK47)),
        PaintKit(342, XOR("Leather"), ENUM2BIT(Weapon::P90)),
        PaintKit(343, XOR("Commuter"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(344, XOR("Dragon Lore"), ENUM2BIT(Weapon::AWP)),
        PaintKit(345, XOR("First Class"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(346, XOR("Coach Class"), ENUM2BIT(Weapon::P2000)),
        PaintKit(347, XOR("Pilot"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(348, XOR("Red Leather"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(349, XOR("Osiris"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(350, XOR("Tigris"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(351, XOR("Conspiracy"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(352, XOR("Fowl Play"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(353, XOR("Water Elemental"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(354, XOR("Urban Hazard"), ENUM2BIT(Weapon::MP7)),
        PaintKit(355, XOR("Desert-Strike"), ENUM2BIT(Weapon::Negev)),
        PaintKit(356, XOR("Koi"), ENUM2BIT(Weapon::Nova)),
        PaintKit(357, XOR("Ivory"), ENUM2BIT(Weapon::P2000)),
        PaintKit(358, XOR("Supernova"), ENUM2BIT(Weapon::P250)),
        PaintKit(359, XOR("Asiimov"), ENUM2BIT(Weapon::P90)),
        PaintKit(360, XOR("Cyrex"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(361, XOR("Abyss"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(362, XOR("Labyrinth"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(363, XOR("Traveler"), ENUM2BIT(Weapon::SG553)),
        PaintKit(364, XOR("Business Class"), ENUM2BIT(Weapon::USPS)),
        PaintKit(365, XOR("Olive Plaid"), ENUM2BIT(Weapon::MP7)),
        PaintKit(366, XOR("Green Plaid"), ENUM2BIT(Weapon::CZ75) | ENUM2BIT(Weapon::MP9)),
        PaintKit(367, XOR("Reactor"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(368, XOR("Setting Sun"), ENUM2BIT(Weapon::MP9)),
        PaintKit(369, XOR("Nuclear Waste"), ENUM2BIT(Weapon::Negev)),
        PaintKit(370, XOR("Bone Machine"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(371, XOR("Styx"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(372, XOR("Nuclear Garden"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(373, XOR("Contamination"), ENUM2BIT(Weapon::P250)),
        PaintKit(374, XOR("Toxic"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(375, XOR("Radiation Hazard"), ENUM2BIT(Weapon::AUG)),
        PaintKit(376, XOR("Chemical Green"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(377, XOR("Hot Shot"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(378, XOR("Fallout Warning"), ENUM2BIT(Weapon::SG553)),
        PaintKit(379, XOR("Cerberus"), ENUM2BIT(Weapon::Galil)),
        PaintKit(380, XOR("Wasteland Rebel"), ENUM2BIT(Weapon::AK47)),
        PaintKit(381, XOR("Grinder"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(382, XOR("Murky"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(383, XOR("Basilisk"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(384, XOR("Griffin"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(385, XOR("Firestarter"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(386, XOR("Dart"), ENUM2BIT(Weapon::MP9)),
        PaintKit(387, XOR("Urban Hazard"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(388, XOR("Cartel"), ENUM2BIT(Weapon::P250)),
        PaintKit(389, XOR("Fire Elemental"), ENUM2BIT(Weapon::P2000)),
        PaintKit(390, XOR("Highwayman"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(391, XOR("Cardiac"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(392, XOR("Delusion"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(393, XOR("Tranquility"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(394, XOR("Cartel"), ENUM2BIT(Weapon::AK47)),
        PaintKit(395, XOR("Man-o'-war"), ENUM2BIT(Weapon::AWP)),
        PaintKit(396, XOR("Urban Shock"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(397, XOR("Naga"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(398, XOR("Chatterbox"), ENUM2BIT(Weapon::Galil)),
        PaintKit(399, XOR("Catacombs"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(400, XOR("Dragon King"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(401, XOR("System Lock"), ENUM2BIT(Weapon::M249)),
        PaintKit(402, XOR("Malachite"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(403, XOR("Deadly Poison"), ENUM2BIT(Weapon::MP9)),
        PaintKit(404, XOR("Muertos"), ENUM2BIT(Weapon::P250)),
        PaintKit(405, XOR("Serenity"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(406, XOR("Grotto"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(407, XOR("Quicksilver"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(422, XOR("Elite Build"), ENUM2BIT(Weapon::AK47)),
        PaintKit(423, XOR("Armor Core"), ENUM2BIT(Weapon::MP7)),
        PaintKit(424, XOR("Worm God"), ENUM2BIT(Weapon::AWP)),
        PaintKit(425, XOR("Bronze Deco"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(426, XOR("Valence"), ENUM2BIT(Weapon::P250)),
        PaintKit(427, XOR("Monkey Business"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(428, XOR("Eco"), ENUM2BIT(Weapon::Galil)),
        PaintKit(429, XOR("Djinn"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(430, XOR("Hyper Beast"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(431, XOR("Heat"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(432, XOR("Man-o'-war"), ENUM2BIT(Weapon::Negev)),
        PaintKit(433, XOR("Neon Rider"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(434, XOR("Origami"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(435, XOR("Pole Position"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(436, XOR("Grand Prix"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(437, XOR("Twilight Galaxy"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(438, XOR("Chronos"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(439, XOR("Hades"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(440, XOR("Icarus Fell"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(441, XOR("Minotaur's Labyrinth"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(442, XOR("Asterion"), ENUM2BIT(Weapon::MP7)),
        PaintKit(443, XOR("Pathfinder"), ENUM2BIT(Weapon::P2000) | ENUM2BIT(Weapon::USPS)),
        PaintKit(444, XOR("Daedalus"), ENUM2BIT(Weapon::AUG)),
        PaintKit(445, XOR("Hot Rod"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(446, XOR("Medusa"), ENUM2BIT(Weapon::AWP)),
        PaintKit(447, XOR("Duelist"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(448, XOR("Pandora's Box"), ENUM2BIT(Weapon::MP9)),
        PaintKit(449, XOR("Poseidon"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(450, XOR("Moon in Libra"), ENUM2BIT(Weapon::DualBerettas) | ENUM2BIT(Weapon::Nova)),
        PaintKit(451, XOR("Sun in Leo"), ENUM2BIT(Weapon::AWP)),
        PaintKit(452, XOR("Shipping Forecast"), ENUM2BIT(Weapon::M249)),
        PaintKit(453, XOR("Emerald"), ENUM2BIT(Weapon::DualBerettas) | ENUM2BIT(Weapon::CZ75)),
        PaintKit(454, XOR("Para Green"), ENUM2BIT(Weapon::USPS)),
        PaintKit(455, XOR("Akihabara Accept"), ENUM2BIT(Weapon::AUG)),
        PaintKit(456, XOR("Hydroponic"), ENUM2BIT(Weapon::AK47)),
        PaintKit(457, XOR("Bamboo Print"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(458, XOR("Bamboo Shadow"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(459, XOR("Bamboo Forest"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(460, XOR("Aqua Terrace"), ENUM2BIT(Weapon::Galil)),
        PaintKit(462, XOR("Counter Terrace"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(463, XOR("Terrace"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(464, XOR("Neon Kimono"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(465, XOR("Orange Kimono"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(466, XOR("Crimson Kimono"), ENUM2BIT(Weapon::P250)),
        PaintKit(467, XOR("Mint Kimono"), ENUM2BIT(Weapon::P250)),
        PaintKit(468, XOR("Midnight Storm"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(469, XOR("Sunset Storm 1"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(470, XOR("Sunset Storm 2"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(471, XOR("Daybreak"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(472, XOR("Impact Drill"), ENUM2BIT(Weapon::M249)),
        PaintKit(473, XOR("Seabird"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(474, XOR("Aquamarine Revenge"), ENUM2BIT(Weapon::AK47)),
        PaintKit(475, XOR("Hyper Beast"), ENUM2BIT(Weapon::AWP)),
        PaintKit(476, XOR("Yellow Jacket"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(477, XOR("Neural Net"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(478, XOR("Rocket Pop"), ENUM2BIT(Weapon::Galil)),
        PaintKit(479, XOR("Bunsen Burner"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(480, XOR("Evil Daimyo"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(481, XOR("Nemesis"), ENUM2BIT(Weapon::MP7)),
        PaintKit(482, XOR("Ruby Poison Dart"), ENUM2BIT(Weapon::MP9)),
        PaintKit(483, XOR("Loudmouth"), ENUM2BIT(Weapon::Negev)),
        PaintKit(484, XOR("Ranger"), ENUM2BIT(Weapon::Nova)),
        PaintKit(485, XOR("Handgun"), ENUM2BIT(Weapon::P2000)),
        PaintKit(486, XOR("Elite Build"), ENUM2BIT(Weapon::P90)),
        PaintKit(487, XOR("Cyrex"), ENUM2BIT(Weapon::SG553)),
        PaintKit(488, XOR("Riot"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(489, XOR("Torque"), ENUM2BIT(Weapon::USPS)),
        PaintKit(490, XOR("Frontside Misty"), ENUM2BIT(Weapon::AK47)),
        PaintKit(491, XOR("Dualing Dragons"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(492, XOR("Survivor Z"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(493, XOR("Flux"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(494, XOR("Stone Cold"), ENUM2BIT(Weapon::Galil)),
        PaintKit(495, XOR("Wraiths"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(496, XOR("Nebula Crusader"), ENUM2BIT(Weapon::M249)),
        PaintKit(497, XOR("Golden Coil"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(498, XOR("Rangeen"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(499, XOR("Cobalt Core"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(500, XOR("Special Delivery"), ENUM2BIT(Weapon::MP7)),
        PaintKit(501, XOR("Wingshot"), ENUM2BIT(Weapon::P250)),
        PaintKit(502, XOR("Green Marine"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(503, XOR("Big Iron"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(504, XOR("Kill Confirmed"), ENUM2BIT(Weapon::USPS)),
        PaintKit(505, XOR("Scumbria"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(506, XOR("Point Disarray"), ENUM2BIT(Weapon::AK47)),
        PaintKit(507, XOR("Ricochet"), ENUM2BIT(Weapon::AUG)),
        PaintKit(508, XOR("Fuel Rod"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(509, XOR("Corinthian"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(510, XOR("Retrobution"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(511, XOR("The Executioner"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(512, XOR("Royal Paladin"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(514, XOR("Power Loader"), ENUM2BIT(Weapon::Negev)),
        PaintKit(515, XOR("Imperial"), ENUM2BIT(Weapon::P2000)),
        PaintKit(516, XOR("Shapewood"), ENUM2BIT(Weapon::P90)),
        PaintKit(517, XOR("Yorick"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(518, XOR("Outbreak"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(519, XOR("Tiger Moth"), ENUM2BIT(Weapon::SG553)),
        PaintKit(520, XOR("Avalanche"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(521, XOR("Teclu Burner"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(522, XOR("Fade"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(523, XOR("Amber Fade"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(524, XOR("Fuel Injector"), ENUM2BIT(Weapon::AK47)),
        PaintKit(525, XOR("Elite Build"), ENUM2BIT(Weapon::AWP)),
        PaintKit(526, XOR("Photic Zone"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(527, XOR("Kumicho Dragon"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(528, XOR("Cartel"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(529, XOR("Valence"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(530, XOR("Triumvirate"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(532, XOR("Royal Legion"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(533, XOR("The Battlestar"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(534, XOR("Lapis Gator"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(535, XOR("Praetorian"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(536, XOR("Impire"), ENUM2BIT(Weapon::MP7)),
        PaintKit(537, XOR("Hyper Beast"), ENUM2BIT(Weapon::Nova)),
        PaintKit(538, XOR("Necropos"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(539, XOR("Jambiya"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(540, XOR("Lead Conduit"), ENUM2BIT(Weapon::USPS)),
        PaintKit(541, XOR("Fleet Flock"), ENUM2BIT(Weapon::AUG)),
        PaintKit(542, XOR("Judgement of Anubis"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(543, XOR("Red Astor"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(544, XOR("Ventilators"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(545, XOR("Orange Crash"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(546, XOR("Firefight"), ENUM2BIT(Weapon::Galil)),
        PaintKit(547, XOR("Spectre"), ENUM2BIT(Weapon::M249)),
        PaintKit(548, XOR("Chantico's Fire"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(549, XOR("Bioleak"), ENUM2BIT(Weapon::MP9)),
        PaintKit(550, XOR("Oceanic"), ENUM2BIT(Weapon::P2000)),
        PaintKit(551, XOR("Asiimov"), ENUM2BIT(Weapon::P250)),
        PaintKit(552, XOR("Fubar"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(553, XOR("Atlas"), ENUM2BIT(Weapon::SG553)),
        PaintKit(554, XOR("Ghost Crusader"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(555, XOR("Re-Entry"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(556, XOR("Primal Saber"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(557, XOR("Black Tie"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(583, XOR("Aristocrat"), ENUM2BIT(Weapon::AUG)),
        PaintKit(584, XOR("Phobos"), ENUM2BIT(Weapon::AWP)),
        PaintKit(585, XOR("Violent Daimyo"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(586, XOR("Wasteland Rebel"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(587, XOR("Mecha Industries"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(588, XOR("Desolate Space"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(589, XOR("Carnivore"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(590, XOR("Exo"), ENUM2BIT(Weapon::Nova)),
        PaintKit(591, XOR("Imperial Dragon"), ENUM2BIT(Weapon::P2000)),
        PaintKit(592, XOR("Iron Clad"), ENUM2BIT(Weapon::P250)),
        PaintKit(593, XOR("Chopper"), ENUM2BIT(Weapon::P90)),
        PaintKit(594, XOR("Harvester"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(595, XOR("Reboot"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(596, XOR("Limelight"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(597, XOR("Bloodsport"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(598, XOR("Aerial"), ENUM2BIT(Weapon::SG553)),
        PaintKit(599, XOR("Ice Cap"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(600, XOR("Neon Revolution"), ENUM2BIT(Weapon::AK47)),
        PaintKit(601, XOR("Syd Mead"), ENUM2BIT(Weapon::AUG)),
        PaintKit(602, XOR("Imprint"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(603, XOR("Directive"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(604, XOR("Roll Cage"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(605, XOR("Scumbria"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(606, XOR("Ventilator"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(607, XOR("Weasel"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(608, XOR("Petroglyph"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(609, XOR("Airlock"), ENUM2BIT(Weapon::MP9)),
        PaintKit(610, XOR("Dazzle"), ENUM2BIT(Weapon::Negev)),
        PaintKit(611, XOR("Grim"), ENUM2BIT(Weapon::P90)),
        PaintKit(612, XOR("Powercore"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(613, XOR("Triarch"), ENUM2BIT(Weapon::SG553)),
        PaintKit(614, XOR("Fuel Injector"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(615, XOR("Briefing"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(616, XOR("Slipstream"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(622, XOR("Polymer"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(623, XOR("Ironwork"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(624, XOR("Dragonfire"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(625, XOR("Royal Consorts"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(626, XOR("Mecha Industries"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(627, XOR("Cirrus"), ENUM2BIT(Weapon::MP7)),
        PaintKit(628, XOR("Stinger"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(629, XOR("Black Sand"), ENUM2BIT(Weapon::Galil)),
        PaintKit(630, XOR("Sand Scale"), ENUM2BIT(Weapon::MP9)),
        PaintKit(631, XOR("Flashback"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(632, XOR("Buzz Kill"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(633, XOR("Sonar"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(634, XOR("Gila"), ENUM2BIT(Weapon::Nova)),
        PaintKit(635, XOR("Turf"), ENUM2BIT(Weapon::P2000)),
        PaintKit(636, XOR("Shallow Grave"), ENUM2BIT(Weapon::P90)),
        PaintKit(637, XOR("Cyrex"), ENUM2BIT(Weapon::USPS)),
        PaintKit(638, XOR("Wasteland Princess"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(639, XOR("Bloodsport"), ENUM2BIT(Weapon::AK47)),
        PaintKit(640, XOR("Fever Dream"), ENUM2BIT(Weapon::AWP)),
        PaintKit(641, XOR("Jungle Slipstream"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(642, XOR("Blueprint"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(643, XOR("Xiangliu"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(644, XOR("Decimator"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(645, XOR("Oxide Blaze"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(646, XOR("Capillary"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(647, XOR("Crimson Tsunami"), ENUM2BIT(Weapon::Galil)),
        PaintKit(648, XOR("Emerald Poison Dart"), ENUM2BIT(Weapon::M249)),
        PaintKit(649, XOR("Akoben"), ENUM2BIT(Weapon::MP7)),
        PaintKit(650, XOR("Ripple"), ENUM2BIT(Weapon::P250)),
        PaintKit(651, XOR("Last Dive"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(652, XOR("Scaffold"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(653, XOR("Neo-Noir"), ENUM2BIT(Weapon::USPS)),
        PaintKit(654, XOR("Seasons"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(655, XOR("Zander"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(656, XOR("Orbit Mk01"), ENUM2BIT(Weapon::AK47)),
        PaintKit(657, XOR("Blueprint"), ENUM2BIT(Weapon::USPS)),
        PaintKit(658, XOR("Cobra Strike"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(659, XOR("Macabre"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(660, XOR("Hyper Beast"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(661, XOR("Sugar Rush"), ENUM2BIT(Weapon::Galil)),
        PaintKit(662, XOR("Oni Taiji"), ENUM2BIT(Weapon::AWP)),
        PaintKit(663, XOR("Briefing"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(664, XOR("Hellfire"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(665, XOR("Aloha"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(666, XOR("Hard Water"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(667, XOR("Woodsman"), ENUM2BIT(Weapon::P2000)),
        PaintKit(668, XOR("Red Rock"), ENUM2BIT(Weapon::P250)),
        PaintKit(669, XOR("Death Grip"), ENUM2BIT(Weapon::P90)),
        PaintKit(670, XOR("Death's Head"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(671, XOR("Cut Out"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(672, XOR("Metal Flowers"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(673, XOR("Morris"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(674, XOR("Triqua"), ENUM2BIT(Weapon::AUG)),
        PaintKit(675, XOR("The Empress"), ENUM2BIT(Weapon::AK47)),
        PaintKit(676, XOR("High Roller"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(677, XOR("Hunter"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(678, XOR("See Ya Later"), ENUM2BIT(Weapon::P250)),
        PaintKit(679, XOR("Goo"), ENUM2BIT(Weapon::MP9)),
        PaintKit(680, XOR("Off World"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(681, XOR("Leaded Glass"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(682, XOR("Oceanic"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(683, XOR("Llama Cannon"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(684, XOR("Cracked Opal"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(685, XOR("Jungle Slipstream"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(686, XOR("Phantom"), ENUM2BIT(Weapon::SG553)),
        PaintKit(687, XOR("Tacticat"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(688, XOR("Exposure"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(689, XOR("Ziggy"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(690, XOR("Stymphalian"), ENUM2BIT(Weapon::AUG)),
        PaintKit(691, XOR("Mortis"), ENUM2BIT(Weapon::AWP)),
        PaintKit(692, XOR("Night Riot"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(693, XOR("Flame Test"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(694, XOR("Moonrise"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(695, XOR("Neo-Noir"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(696, XOR("Bloodsport"), ENUM2BIT(Weapon::MP7)),
        PaintKit(697, XOR("Black Sand"), ENUM2BIT(Weapon::MP9)),
        PaintKit(698, XOR("Lionfish"), ENUM2BIT(Weapon::Negev)),
        PaintKit(699, XOR("Wild Six"), ENUM2BIT(Weapon::Nova)),
        PaintKit(700, XOR("Urban Hazard"), ENUM2BIT(Weapon::P2000)),
        PaintKit(701, XOR("Grip"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(702, XOR("Aloha"), ENUM2BIT(Weapon::SG553)),
        PaintKit(703, XOR("SWAG-7"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(704, XOR("Arctic Wolf"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(705, XOR("Cortex"), ENUM2BIT(Weapon::USPS)),
        PaintKit(706, XOR("Oxide Blaze"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(707, XOR("Neon Rider"), ENUM2BIT(Weapon::AK47)),
        PaintKit(708, XOR("Amber Slipstream"), ENUM2BIT(Weapon::AUG)),
        PaintKit(709, XOR("Eco"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(710, XOR("Shred"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(711, XOR("Code Red"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(712, XOR("High Seas"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(713, XOR("Warhawk"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(714, XOR("Nightmare"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(715, XOR("Capillary"), ENUM2BIT(Weapon::MP9)),
        PaintKit(716, XOR("Toy Soldier"), ENUM2BIT(Weapon::Nova)),
        PaintKit(717, XOR("Traction"), ENUM2BIT(Weapon::P90)),
        PaintKit(718, XOR("PAW"), ENUM2BIT(Weapon::AWP)),
        PaintKit(719, XOR("Powercore"), ENUM2BIT(Weapon::MP7)),
        PaintKit(720, XOR("Devourer"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(721, XOR("Survivalist"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(722, XOR("Snek-9"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(723, XOR("Eye of Athena"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(724, XOR("Wild Lotus"), ENUM2BIT(Weapon::AK47)),
        PaintKit(725, XOR("Day Lily"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(726, XOR("Sunset Lily"), ENUM2BIT(Weapon::P90)),
        PaintKit(727, XOR("Midnight Lily"), ENUM2BIT(Weapon::AUG)),
        PaintKit(728, XOR("Teal Blossom"), ENUM2BIT(Weapon::MP7)),
        PaintKit(729, XOR("Crimson Blossom"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(730, XOR("Dark Blossom"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(731, XOR("Banana Leaf"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(732, XOR("Synth Leaf"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(733, XOR("Rust Leaf"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(734, XOR("Wild Lily"), ENUM2BIT(Weapon::MP9)),
        PaintKit(736, XOR("The Prince"), ENUM2BIT(Weapon::AWP)),
        PaintKit(737, XOR("Cinquedea"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(738, XOR("Orange Murano"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(739, XOR("Violet Murano"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(740, XOR("Navy Murano"), ENUM2BIT(Weapon::AUG)),
        PaintKit(741, XOR("Dark Filigree"), ENUM2BIT(Weapon::P250)),
        PaintKit(742, XOR("Red Filigree"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(743, XOR("Orange Filigree"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(744, XOR("Baroque Red"), ENUM2BIT(Weapon::P90)),
        PaintKit(745, XOR("Baroque Purple"), ENUM2BIT(Weapon::AK47)),
        PaintKit(746, XOR("Baroque Orange"), ENUM2BIT(Weapon::Nova)),
        PaintKit(747, XOR("Twin Turbo"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(748, XOR("Calf Skin"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(749, XOR("Vino Primo"), ENUM2BIT(Weapon::P250)),
        PaintKit(750, XOR("Integrale"), ENUM2BIT(Weapon::SG553)),
        PaintKit(751, XOR("Hand Brake"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(752, XOR("Fade"), ENUM2BIT(Weapon::MP7)),
        PaintKit(753, XOR("Dirt Drop"), ENUM2BIT(Weapon::MP5)),
        PaintKit(754, XOR("Rust Coat"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(755, XOR("Slide"), ENUM2BIT(Weapon::MP9)),
        PaintKit(756, XOR("Gungnir"), ENUM2BIT(Weapon::AWP)),
        PaintKit(757, XOR("Emerald Jörmungandr"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(758, XOR("Flame Jörmungandr"), ENUM2BIT(Weapon::AUG)),
        PaintKit(759, XOR("Astral Jörmungandr"), ENUM2BIT(Weapon::P90)),
        PaintKit(760, XOR("Frost Borre"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(761, XOR("Copper Borre"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(762, XOR("Red Stone"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(763, XOR("Mjölnir"), ENUM2BIT(Weapon::Negev)),
        PaintKit(775, XOR("Facility Sketch"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(776, XOR("Facility Negative"), ENUM2BIT(Weapon::P90)),
        PaintKit(777, XOR("Facility Draft"), ENUM2BIT(Weapon::P250)),
        PaintKit(778, XOR("Facility Dark"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(779, XOR("Random Access"), ENUM2BIT(Weapon::AUG)),
        PaintKit(780, XOR("Mainframe"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(781, XOR("Co-Processor"), ENUM2BIT(Weapon::MP5)),
        PaintKit(782, XOR("Motherboard"), ENUM2BIT(Weapon::MP7)),
        PaintKit(783, XOR("Bulkhead"), ENUM2BIT(Weapon::Negev)),
        PaintKit(784, XOR("Coolant"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(785, XOR("Mandrel"), ENUM2BIT(Weapon::Nova)),
        PaintKit(786, XOR("Exchanger"), ENUM2BIT(Weapon::P250)),
        PaintKit(787, XOR("Core Breach"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(788, XOR("Acheron"), ENUM2BIT(Weapon::AWP)),
        PaintKit(789, XOR("Nuclear Garden"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(790, XOR("Cold Fusion"), ENUM2BIT(Weapon::Galil)),
        PaintKit(791, XOR("Remote Control"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(792, XOR("Control Panel"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(793, XOR("Converter"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(794, XOR("Sweeper"), ENUM2BIT(Weapon::AUG)),
        PaintKit(795, XOR("Safety Net"), ENUM2BIT(Weapon::AK47)),
        PaintKit(796, XOR("Check Engine"), ENUM2BIT(Weapon::USPS)),
        PaintKit(797, XOR("Brake Light"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(798, XOR("Nitro"), ENUM2BIT(Weapon::R8Revolver) | ENUM2BIT(Weapon::MP5)),
        PaintKit(799, XOR("High Beam"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(800, XOR("Lab Rats"), ENUM2BIT(Weapon::MP5)),
        PaintKit(801, XOR("Asiimov"), ENUM2BIT(Weapon::AK47)),
        PaintKit(802, XOR("Momentum"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(803, XOR("Neo-Noir"), ENUM2BIT(Weapon::AWP)),
        PaintKit(804, XOR("Modest Threat"), ENUM2BIT(Weapon::MP9)),
        PaintKit(805, XOR("Mecha Industries"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(806, XOR("Scavenger"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(807, XOR("Signal"), ENUM2BIT(Weapon::Galil)),
        PaintKit(808, XOR("Oxide Blaze"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(809, XOR("Wood Fired"), ENUM2BIT(Weapon::Nova)),
        PaintKit(810, XOR("Phosphor"), ENUM2BIT(Weapon::MP5)),
        PaintKit(811, XOR("Magnesium"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(812, XOR("Pipe Down"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(813, XOR("Nevermore"), ENUM2BIT(Weapon::P250)),
        PaintKit(814, XOR("Black Sand"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(815, XOR("Danger Close"), ENUM2BIT(Weapon::SG553)),
        PaintKit(816, XOR("Fubar"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(817, XOR("Flashback"), ENUM2BIT(Weapon::USPS)),
        PaintKit(835, XOR("Crypsis"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(836, XOR("Uncharted"), ENUM2BIT(Weapon::AK47)),
        PaintKit(837, XOR("Angry Mob"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(838, XOR("Atheris"), ENUM2BIT(Weapon::AWP)),
        PaintKit(839, XOR("Bamboozle"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(840, XOR("Whitefish"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(841, XOR("Light Rail"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(842, XOR("Akoben"), ENUM2BIT(Weapon::Galil)),
        PaintKit(843, XOR("Skull Crusher"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(844, XOR("The Emperor"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(845, XOR("Momentum"), ENUM2BIT(Weapon::AUG)),
        PaintKit(846, XOR("Gauss"), ENUM2BIT(Weapon::MP5)),
        PaintKit(847, XOR("Mischief"), ENUM2BIT(Weapon::MP7)),
        PaintKit(848, XOR("Verdigris"), ENUM2BIT(Weapon::P250)),
        PaintKit(849, XOR("Off World"), ENUM2BIT(Weapon::P90)),
        PaintKit(850, XOR("Incinegator"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(851, XOR("Moonrise"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(859, XOR("Emerald Quartz"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(860, XOR("Pyre"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(861, XOR("Barricade"), ENUM2BIT(Weapon::SG553)),
        PaintKit(862, XOR("Moss Quartz"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(863, XOR("Night Borre"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(864, XOR("Candy Apple"), ENUM2BIT(Weapon::SG553)),
        PaintKit(865, XOR("Stone Mosaico"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(866, XOR("Canal Spray"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(867, XOR("Stained Glass"), ENUM2BIT(Weapon::MP9)),
        PaintKit(868, XOR("Sea Calico"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(869, XOR("Sundown"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(870, XOR("Jungle Thicket"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(871, XOR("Surfwood"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(872, XOR("Bamboo Garden"), ENUM2BIT(Weapon::MP5)),
        PaintKit(873, XOR("Seabird"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(884, XOR("Embargo"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(885, XOR("Rat Rod"), ENUM2BIT(Weapon::AK47)),
        PaintKit(886, XOR("Arctic Wolf"), ENUM2BIT(Weapon::AUG)),
        PaintKit(887, XOR("Containment Breach"), ENUM2BIT(Weapon::AWP)),
        PaintKit(888, XOR("Acid Wash"), ENUM2BIT(Weapon::MP5)),
        PaintKit(889, XOR("Decimator"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(890, XOR("Plume"), ENUM2BIT(Weapon::Nova)),
        PaintKit(891, XOR("Black Sand"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(892, XOR("Memento"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(893, XOR("Neon Ply"), ENUM2BIT(Weapon::MP7)),
        PaintKit(894, XOR("Obsidian"), ENUM2BIT(Weapon::P2000)),
        PaintKit(895, XOR("Balance"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(896, XOR("Torn"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(897, XOR("Colony IV"), ENUM2BIT(Weapon::SG553)),
        PaintKit(898, XOR("Stalker"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(899, XOR("Bloodshot"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(900, XOR("Warbird"), ENUM2BIT(Weapon::M249)),
        PaintKit(902, XOR("Aztec"), ENUM2BIT(Weapon::M249)),
        PaintKit(903, XOR("Elite 1.6"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(904, XOR("Decommissioned"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(905, XOR("Flash Out"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(906, XOR("Buddy"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(907, XOR("Inferno"), ENUM2BIT(Weapon::P250)),
        PaintKit(908, XOR("Classic Crate"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(909, XOR("Popdog"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(910, XOR("Hydra"), ENUM2BIT(Weapon::MP9)),
        PaintKit(911, XOR("Nostalgia"), ENUM2BIT(Weapon::P90)),
        PaintKit(913, XOR("Death by Puppy"), ENUM2BIT(Weapon::AUG)),
        PaintKit(914, XOR("Assault"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(915, XOR("Agent"), ENUM2BIT(Weapon::MP5)),
        PaintKit(916, XOR("Plastique"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(917, XOR("Wildfire"), ENUM2BIT(Weapon::AWP)),
        PaintKit(918, XOR("Sacrifice"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(919, XOR("Commemoration"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(920, XOR("Boroque Sand"), ENUM2BIT(Weapon::Negev)),
        PaintKit(941, XOR("Phantom Disruptor"), ENUM2BIT(Weapon::AK47)),
        PaintKit(942, XOR("Tom Cat"), ENUM2BIT(Weapon::AUG)),
        PaintKit(943, XOR("Capillary"), ENUM2BIT(Weapon::AWP)),
        PaintKit(944, XOR("Distressed"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(945, XOR("Blue Ply"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(946, XOR("Player Two"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(947, XOR("Disco Tech"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(948, XOR("Justice"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(949, XOR("Desert Strike"), ENUM2BIT(Weapon::MP5)),
        PaintKit(950, XOR("Prototype"), ENUM2BIT(Weapon::Negev)),
        PaintKit(951, XOR("Acid Etched"), ENUM2BIT(Weapon::P2000)),
        PaintKit(952, XOR("Bone Forged"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(953, XOR("Apocalypto"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(954, XOR("Enforcer"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(955, XOR("Darkwing"), ENUM2BIT(Weapon::SG553)),
        PaintKit(956, XOR("Fever Dream"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(957, XOR("Bullet Queen"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(958, XOR("Ultralight"), ENUM2BIT(Weapon::Negev)),
        PaintKit(959, XOR("Legion of Anubis"), ENUM2BIT(Weapon::AK47)),
        PaintKit(960, XOR("Gnarled"), ENUM2BIT(Weapon::P2000)),
        PaintKit(961, XOR("Monster Call"), ENUM2BIT(Weapon::MAG7)),
        PaintKit(962, XOR("Printstream"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(963, XOR("Vogue"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(964, XOR("Brother"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(965, XOR("Allure"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(966, XOR("Ol' Rusty"), ENUM2BIT(Weapon::SG553)),
        PaintKit(967, XOR("Mainframe 001"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(968, XOR("Cassette"), ENUM2BIT(Weapon::P250)),
        PaintKit(969, XOR("Freight"), ENUM2BIT(Weapon::P90)),
        PaintKit(970, XOR("Entombed"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(971, XOR("Tooth Fairy"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(972, XOR("Connexion"), ENUM2BIT(Weapon::Galil)),
        PaintKit(973, XOR("Runic"), ENUM2BIT(Weapon::PPBizon)),
        PaintKit(974, XOR("Kitbash"), ENUM2BIT(Weapon::MP5)),
        PaintKit(975, XOR("Exoskeleton"), ENUM2BIT(Weapon::AWP)),
        PaintKit(976, XOR("Vendetta"), ENUM2BIT(Weapon::CZ75)),
        PaintKit(977, XOR("Cocoa Rampage"), ENUM2BIT(Weapon::P90)),
        PaintKit(978, XOR("Dezastre"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(979, XOR("Fairy Tale"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(980, XOR("Digital Mesh"), ENUM2BIT(Weapon::G3SG1)),
        PaintKit(981, XOR("Vandal"), ENUM2BIT(Weapon::Galil)),
        PaintKit(982, XOR("Contaminant"), ENUM2BIT(Weapon::P250)),
        PaintKit(983, XOR("Deep Relief"), ENUM2BIT(Weapon::M249)),
        PaintKit(984, XOR("Printstream"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(985, XOR("Cyber Security"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(986, XOR("Condition Zero"), ENUM2BIT(Weapon::MP5)),
        PaintKit(987, XOR("Clear Polymer"), ENUM2BIT(Weapon::Nova)),
        PaintKit(988, XOR("Neo-Noir"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(989, XOR("Parallax"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(990, XOR("Gold Bismuth"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(991, XOR("Monster Mashup"), ENUM2BIT(Weapon::USPS)),
        PaintKit(992, XOR("The Bronze"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(993, XOR("Global Offensive"), ENUM2BIT(Weapon::M4A4)),
        PaintKit(994, XOR("Charter"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(995, XOR("Surveillance"), ENUM2BIT(Weapon::AUG)),
        PaintKit(996, XOR("Threat Detected"), ENUM2BIT(Weapon::SSG08)),
        PaintKit(997, XOR("Dispatch"), ENUM2BIT(Weapon::P2000)),
        PaintKit(998, XOR("Switch Board"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(999, XOR("Prime Conspiracy"), ENUM2BIT(Weapon::FAMAS)),
        PaintKit(1000, XOR("Run and Hide"), ENUM2BIT(Weapon::P90)),
        PaintKit(1001, XOR("Welcome to the Jungle"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(1002, XOR("Berries And Cherries"), ENUM2BIT(Weapon::FiveSeven)),
        PaintKit(1003, XOR("Crime Scene"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(1004, XOR("X-Ray"), ENUM2BIT(Weapon::AK47)),
        PaintKit(1005, XOR("Heist"), ENUM2BIT(Weapon::DualBerettas)),
        PaintKit(1006, XOR("Night Heist"), ENUM2BIT(Weapon::DesertEagle)),
        PaintKit(1007, XOR("Vault Heist"), ENUM2BIT(Weapon::MP7)),
        PaintKit(1008, XOR("Houndstooth"), ENUM2BIT(Weapon::UMP45)),
        PaintKit(1009, XOR("Hot Snakes"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(1010, XOR("Phoenix Chalk"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(1011, XOR("Phoenix Marker"), ENUM2BIT(Weapon::R8Revolver)),
        PaintKit(1012, XOR("Phoenix Stencil"), ENUM2BIT(Weapon::Negev)),
        PaintKit(1013, XOR("Phoenix Blacklight"), ENUM2BIT(Weapon::Galil)),
        PaintKit(1014, XOR("Clay Ambush"), ENUM2BIT(Weapon::SawedOff)),
        PaintKit(1015, XOR("Tiger Pit"), ENUM2BIT(Weapon::P90)),
        PaintKit(1016, XOR("Franklin"), ENUM2BIT(Weapon::Glock18)),
        PaintKit(1017, XOR("Blue Phosphor"), ENUM2BIT(Weapon::M4A1S)),
        PaintKit(1018, XOR("Panthera onca"), ENUM2BIT(Weapon::AK47)),
        PaintKit(1019, XOR("Panther Camo"), ENUM2BIT(Weapon::P2000)),
        PaintKit(1020, XOR("Ancient Earth"), ENUM2BIT(Weapon::P90)),
        PaintKit(1021, XOR("Ancient Lore"), ENUM2BIT(Weapon::XM1014)),
        PaintKit(1022, XOR("Lush Ruins"), ENUM2BIT(Weapon::SG553)),
        PaintKit(1023, XOR("Tall Grass"), ENUM2BIT(Weapon::MP7)),
        PaintKit(1024, XOR("Blast From the Past"), ENUM2BIT(Weapon::Tec9)),
        PaintKit(1025, XOR("Gold Brick"), ENUM2BIT(Weapon::MAC10)),
        PaintKit(1026, XOR("Fade"), ENUM2BIT(Weapon::AWP)),
        PaintKit(1027, XOR("Target Acquired"), ENUM2BIT(Weapon::USPS)),
        PaintKit(1028, XOR("Magna Carta"), ENUM2BIT(Weapon::SCAR20)),
        PaintKit(1029, XOR("Silk Tiger"), ENUM2BIT(Weapon::AWP)),
        PaintKit(1030, XOR("Bengal Tiger"), ENUM2BIT(Weapon::P250)),
        PaintKit(1031, XOR("Ancient Visions"), ENUM2BIT(Weapon::USPS)),
        PaintKit(1032, XOR("Dusk Ruins"), ENUM2BIT(Weapon::Galil)),
        PaintKit(1033, XOR("Carved Jade"), ENUM2BIT(Weapon::AUG)),
        PaintKit(1034, XOR("Ancient Ritual"), ENUM2BIT(Weapon::G3SG1)),


#define ALLKNIVESLMAO 0xFFFFFFFFFFFFFFFFull

        PaintKit(413, XOR("Marble Fade")        , 0, ALLKNIVESLMAO),
        PaintKit(418, XOR("Doppler Phase 1")    , 0, ALLKNIVESLMAO),
        PaintKit(618, XOR("Doppler Phase 2")    , 0, ALLKNIVESLMAO),
        PaintKit(420, XOR("Doppler Phase 3")    , 0, ALLKNIVESLMAO),
        PaintKit(421, XOR("Doppler Phase 4")    , 0, ALLKNIVESLMAO),
        PaintKit(415, XOR("Ruby Doppler")       , 0, ALLKNIVESLMAO),
        PaintKit(619, XOR("Sapphire Doppler")   , 0, ALLKNIVESLMAO),
        PaintKit(617, XOR("Black Pearl Doppler"), 0, ALLKNIVESLMAO),
	};
#undef ENUM2BIT
    PaintKit* PaintKitFromID(int ID)
    {
        for (size_t i = 0; i < PaintKits.size(); i++)
            if (PaintKits.at(i).ID == ID) return &PaintKits.at(i);
        return nullptr;
    }

    constexpr Weapon WeaponFromId(WeaponId id)
    {
        switch (id)
        {
        default: return Weapon::INVALID;
        case WeaponId::DesertEagle:   return Weapon::DesertEagle;
        case WeaponId::DualBerettas:  return Weapon::DualBerettas;
        case WeaponId::FiveSeveN:     return Weapon::FiveSeven;
        case WeaponId::Glock18:       return Weapon::Glock18;
        case WeaponId::AK47:          return Weapon::AK47;
        case WeaponId::AUG:           return Weapon::AUG;
        case WeaponId::AWP:           return Weapon::AWP;
        case WeaponId::FAMAS:         return Weapon::FAMAS;
        case WeaponId::G3SG1:         return Weapon::G3SG1;
        case WeaponId::GalilAR:       return Weapon::Galil;
        case WeaponId::M249:          return Weapon::M249;
        case WeaponId::M4A4:          return Weapon::M4A4;
        case WeaponId::MAC10:         return Weapon::MAC10;
        case WeaponId::P90:           return Weapon::P90;
        case WeaponId::MP5SD:         return Weapon::MP5;
        case WeaponId::UMP45:         return Weapon::UMP45;
        case WeaponId::XM1014:        return Weapon::XM1014;
        case WeaponId::PPBizon:       return Weapon::PPBizon;
        case WeaponId::MAG7:          return Weapon::MAG7;
        case WeaponId::Negev:         return Weapon::Negev;
        case WeaponId::SawedOff:      return Weapon::SawedOff;
        case WeaponId::Tec9:          return Weapon::Tec9;
        case WeaponId::Zeusx27:       return Weapon::Zeus;
        case WeaponId::P2000:         return Weapon::P2000;
        case WeaponId::MP7:           return Weapon::MP7;
        case WeaponId::MP9:           return Weapon::MP9;
        case WeaponId::Nova:          return Weapon::Nova;
        case WeaponId::P250:          return Weapon::P250;
        case WeaponId::SCAR20:        return Weapon::SCAR20;
        case WeaponId::SG553:         return Weapon::SG553;
        case WeaponId::SSG08:         return Weapon::SSG08;
        case WeaponId::M4A1S:         return Weapon::M4A1S;
        case WeaponId::USPS:          return Weapon::USPS;
        case WeaponId::CZ75Auto:      return Weapon::CZ75;
        case WeaponId::R8Revolver:    return Weapon::R8Revolver;
         // other...
        case WeaponId::C4Explosive:           return Weapon::C4;
        case WeaponId::IncendiaryGrenade:     return Weapon::Incendiary;
        case WeaponId::Molotov:               return Weapon::Molotov;
        case WeaponId::DecoyGrenade:          return Weapon::Decoy;
        case WeaponId::Flashbang:             return Weapon::Flashbang;
        case WeaponId::HighExplosiveGrenade:  return Weapon::HE;
        case WeaponId::SmokeGrenade:          return Weapon::Smoke;
        }
    }
    constexpr Knife KnifeFromId(WeaponId id)
    {
        switch (id)
        {
        default: return Knife::INVALID;

        case WeaponId::NomadKnife: return Knife::Nomad;
        case WeaponId::SkeletonKnife: return Knife::Skeleton;
        case WeaponId::SurvivalKnife: return Knife::Survival;
        case WeaponId::ParacordKnife: return Knife::Paracord;
        case WeaponId::ClassicKnife: return Knife::Classic;
        case WeaponId::BowieKnife: return Knife::Bowie;
        case WeaponId::ButterflyKnife: return Knife::Butterfly;
        case WeaponId::FalchionKnife: return Knife::Falchion;
        case WeaponId::FlipKnife: return Knife::Flip;
        case WeaponId::GutKnife: return Knife::Gut;
        case WeaponId::HuntsmanKnife: return Knife::Huntsman;
        case WeaponId::Karambit: return Knife::Karambit;
        case WeaponId::Bayonet: return Knife::Bayonet;
        case WeaponId::M9Bayonet: return Knife::M9Bayonet;
        case WeaponId::NavajaKnife: return Knife::Navaja;
        case WeaponId::ShadowDaggers: return Knife::ShadowDaggers;
        case WeaponId::StilettoKnife: return Knife::Stiletto;
        case WeaponId::TalonKnife: return Knife::Talon;
        case WeaponId::UrsusKnife: return Knife::Ursus;
        case WeaponId::TDefaultKnife: return Knife::TDefault;
        case WeaponId::CTDefaultKnife: return Knife::CTDefault;
        }
    }
    constexpr WeaponId IdFromKnife(Knife k)
    {
        switch (k)
        {
        default: return WeaponId::INVALID;

        case Knife::Nomad:         return WeaponId::NomadKnife;
        case Knife::Skeleton:      return WeaponId::SkeletonKnife;
        case Knife::Survival:      return WeaponId::SurvivalKnife;
        case Knife::Paracord:      return WeaponId::ParacordKnife;
        case Knife::Classic:       return WeaponId::ClassicKnife;
        case Knife::Bowie:         return WeaponId::BowieKnife;
        case Knife::Butterfly:     return WeaponId::ButterflyKnife;
        case Knife::Falchion:      return WeaponId::FalchionKnife;
        case Knife::Flip:          return WeaponId::FlipKnife;
        case Knife::Gut:           return WeaponId::GutKnife;
        case Knife::Huntsman:      return WeaponId::HuntsmanKnife;
        case Knife::Karambit:      return WeaponId::Karambit;
        case Knife::Bayonet:       return WeaponId::Bayonet;
        case Knife::M9Bayonet:     return WeaponId::M9Bayonet;
        case Knife::Navaja:        return WeaponId::NavajaKnife;
        case Knife::ShadowDaggers: return WeaponId::ShadowDaggers;
        case Knife::Stiletto:      return WeaponId::StilettoKnife;
        case Knife::Talon:         return WeaponId::TalonKnife;
        case Knife::Ursus:         return WeaponId::UrsusKnife;
        case Knife::TDefault:      return WeaponId::TDefaultKnife;
        case Knife::CTDefault:     return WeaponId::CTDefaultKnife;
        }
    }
    constexpr const char* GetKnifeModel(Knife knife)
    {
        switch (knife)
        {
        default: return "";

        case Knife::Nomad:         return "models/weapons/v_knife_outdoor.mdl";
        case Knife::Skeleton:      return "models/weapons/v_knife_skeleton.mdl";
        case Knife::Survival:      return "models/weapons/v_knife_canis.mdl";
        case Knife::Paracord:      return "models/weapons/v_knife_cord.mdl";
        case Knife::Classic:       return "models/weapons/v_knife_css.mdl";
        case Knife::Bowie:         return "models/weapons/v_knife_survival_bowie.mdl";
        case Knife::Butterfly:     return "models/weapons/v_knife_butterfly.mdl";
        case Knife::Falchion:      return "models/weapons/v_knife_falchion_advanced.mdl";
        case Knife::Flip:          return "models/weapons/v_knife_flip.mdl";
        case Knife::Gut:           return "models/weapons/v_knife_gut.mdl";
        case Knife::Huntsman:      return "models/weapons/v_knife_tactical.mdl";
        case Knife::Karambit:      return "models/weapons/v_knife_karam.mdl";
        case Knife::Bayonet:       return "models/weapons/v_knife_bayonet.mdl";
        case Knife::M9Bayonet:     return "models/weapons/v_knife_m9_bay.mdl";
        case Knife::Navaja:        return "models/weapons/v_knife_gypsy_jackknife.mdl";
        case Knife::ShadowDaggers: return "models/weapons/v_knife_push.mdl";
        case Knife::Stiletto:      return "models/weapons/v_knife_stiletto.mdl";
        case Knife::Talon:         return "models/weapons/v_knife_widowmaker.mdl";
        case Knife::Ursus:         return "models/weapons/v_knife_ursus.mdl";
        case Knife::TDefault:      return "models/weapons/v_knife_default_t.mdl";
        case Knife::CTDefault:     return "models/weapons/v_knife_default_ct.mdl";
        }
    }
};